// VTK Module Initialization
//
// This file provides explicit initialization of VTK modules for Rust bindings.
//
// WHY THIS IS NEEDED:
// - VTK uses an "AutoInit" system to register object factories at startup
// - This works via C++ static initializers in each module
// - When linking static libraries (.a files), static initializers don't run
//   unless something references them explicitly
// - This file provides that explicit reference by calling the AutoInit
//   constructors manually from Rust
//
// The `vtk_module_autoinit` CMake function generates these constructor
// functions, but we need to call them explicitly to trigger registration.

#include <vtkAutoInit.h>

// Handle VTK version differences: ABI namespace macros only exist in VTK 9.2+
#ifndef VTK_ABI_NAMESPACE_BEGIN
#define VTK_ABI_NAMESPACE_BEGIN
#define VTK_ABI_NAMESPACE_END
#endif

// Forward declarations for AutoInit constructor functions
// These are generated by the vtk_module_autoinit CMake function
VTK_ABI_NAMESPACE_BEGIN
extern void vtkRenderingContextOpenGL2_AutoInit_Construct();
extern void vtkInteractionStyle_AutoInit_Construct();
extern void vtkRenderingFreeType_AutoInit_Construct();
extern void vtkRenderingOpenGL2_AutoInit_Construct();
extern void vtkRenderingGL2PSOpenGL2_AutoInit_Construct();
// Note: RenderingAnnotation and InteractionWidgets don't export AutoInit functions
// in Homebrew's dynamically linked VTK build
VTK_ABI_NAMESPACE_END

/// Manually trigger VTK module initialization.
/// MUST be called before creating any VTK objects.
/// This is automatically called from Rust via the define_object! macro.
extern "C" void vtk_force_init() {
    // Call each module's AutoInit constructor
    // This registers the object factories needed for VTK::New() to work
    vtkRenderingContextOpenGL2_AutoInit_Construct();
    vtkInteractionStyle_AutoInit_Construct();
    vtkRenderingFreeType_AutoInit_Construct();
    vtkRenderingOpenGL2_AutoInit_Construct();
    vtkRenderingGL2PSOpenGL2_AutoInit_Construct();
}

