cxxbridge --header >libvtkrs/include/cxx.h

for file in src/vtk_*.rs; do
    cxxbridge $file >$file.h
    # Add comment at the beginning of the file (macOS compatible)
    printf "// AUTO-GENERATED BY cxxbridge\n%s" "$(cat $file.h)" > $file.h
    mv $file.h libvtkrs/include
done
