// AUTO-GENERATED BY cxxbridge
#include "vtk_render_window_interactor.h"
#include "vtk_render_window.h"

#ifdef __GNUC__
#pragma GCC diagnostic ignored "-Wmissing-declarations"
#ifdef __clang__
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"
#endif // __clang__
#endif // __GNUC__

using vtkRenderWindowInteractor = ::vtkRenderWindowInteractor;
using vtkRenderWindow = ::vtkRenderWindow;
using vtkInteractorStyle = ::vtkInteractorStyle;

extern "C" {
::vtkRenderWindowInteractor *cxxbridge1$192$render_window_interactor_new() noexcept {
  ::vtkRenderWindowInteractor *(*render_window_interactor_new$)() = ::render_window_interactor_new;
  return render_window_interactor_new$();
}

void cxxbridge1$192$render_window_interactor_delete(::vtkRenderWindowInteractor &interactor) noexcept {
  void (*render_window_interactor_delete$)(::vtkRenderWindowInteractor &) = ::render_window_interactor_delete;
  render_window_interactor_delete$(interactor);
}

void cxxbridge1$192$render_window_interactor_set_render_window(::vtkRenderWindowInteractor &interactor, ::vtkRenderWindow *window) noexcept {
  void (*render_window_interactor_set_render_window$)(::vtkRenderWindowInteractor &, ::vtkRenderWindow *) = ::render_window_interactor_set_render_window;
  render_window_interactor_set_render_window$(interactor, window);
}

void cxxbridge1$192$render_window_interactor_set_interactor_style(::vtkRenderWindowInteractor &interactor, ::vtkInteractorStyle *style) noexcept {
  void (*render_window_interactor_set_interactor_style$)(::vtkRenderWindowInteractor &, ::vtkInteractorStyle *) = ::render_window_interactor_set_interactor_style;
  render_window_interactor_set_interactor_style$(interactor, style);
}

void cxxbridge1$192$render_window_interactor_initialize(::vtkRenderWindowInteractor &interactor) noexcept {
  void (*render_window_interactor_initialize$)(::vtkRenderWindowInteractor &) = ::render_window_interactor_initialize;
  render_window_interactor_initialize$(interactor);
}

void cxxbridge1$192$render_window_interactor_start(::vtkRenderWindowInteractor &interactor) noexcept {
  void (*render_window_interactor_start$)(::vtkRenderWindowInteractor &) = ::render_window_interactor_start;
  render_window_interactor_start$(interactor);
}
} // extern "C"