// AUTO-GENERATED BY cxxbridge
#include "vtk_parametric_mobius.h"
#include "vtk_parametric_function.h"

#ifdef __GNUC__
#pragma GCC diagnostic ignored "-Wmissing-declarations"
#ifdef __clang__
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"
#endif // __clang__
#endif // __GNUC__

using vtkParametricMobius = ::vtkParametricMobius;
using vtkParametricFunction = ::vtkParametricFunction;

extern "C" {
::vtkParametricMobius *cxxbridge1$192$vtk_parametric_mobius_new() noexcept {
  ::vtkParametricMobius *(*vtk_parametric_mobius_new$)() = ::vtk_parametric_mobius_new;
  return vtk_parametric_mobius_new$();
}

void cxxbridge1$192$vtk_parametric_mobius_delete(::vtkParametricMobius &ptr) noexcept {
  void (*vtk_parametric_mobius_delete$)(::vtkParametricMobius &) = ::vtk_parametric_mobius_delete;
  vtk_parametric_mobius_delete$(ptr);
}

void cxxbridge1$192$parametric_mobius_set_radius(::vtkParametricMobius &mobius, double radius) noexcept {
  void (*parametric_mobius_set_radius$)(::vtkParametricMobius &, double) = ::parametric_mobius_set_radius;
  parametric_mobius_set_radius$(mobius, radius);
}

double cxxbridge1$192$parametric_mobius_get_radius(::vtkParametricMobius const &mobius) noexcept {
  double (*parametric_mobius_get_radius$)(::vtkParametricMobius const &) = ::parametric_mobius_get_radius;
  return parametric_mobius_get_radius$(mobius);
}

::vtkParametricFunction *cxxbridge1$192$parametric_mobius_as_parametric_function(::vtkParametricMobius &mobius) noexcept {
  ::vtkParametricFunction *(*parametric_mobius_as_parametric_function$)(::vtkParametricMobius &) = ::parametric_mobius_as_parametric_function;
  return parametric_mobius_as_parametric_function$(mobius);
}
} // extern "C"