// AUTO-GENERATED BY cxxbridge
#include "vtk_cylinder_source.h"
#include "vtk_algorithm_output.h"
#include <cstdint>

#ifdef __GNUC__
#pragma GCC diagnostic ignored "-Wmissing-declarations"
#ifdef __clang__
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"
#endif // __clang__
#endif // __GNUC__

using vtkCylinderSource = ::vtkCylinderSource;
using vtkAlgorithmOutput = ::vtkAlgorithmOutput;

extern "C" {
::vtkCylinderSource *cxxbridge1$192$vtk_cylinder_source_new() noexcept {
  ::vtkCylinderSource *(*vtk_cylinder_source_new$)() = ::vtk_cylinder_source_new;
  return vtk_cylinder_source_new$();
}

void cxxbridge1$192$vtk_cylinder_source_delete(::vtkCylinderSource &cylinder) noexcept {
  void (*vtk_cylinder_source_delete$)(::vtkCylinderSource &) = ::vtk_cylinder_source_delete;
  vtk_cylinder_source_delete$(cylinder);
}

void cxxbridge1$192$vtk_cylinder_source_set_radius(::vtkCylinderSource &cylinder, double radius) noexcept {
  void (*vtk_cylinder_source_set_radius$)(::vtkCylinderSource &, double) = ::vtk_cylinder_source_set_radius;
  vtk_cylinder_source_set_radius$(cylinder, radius);
}

double cxxbridge1$192$vtk_cylinder_source_get_radius(::vtkCylinderSource const &cylinder) noexcept {
  double (*vtk_cylinder_source_get_radius$)(::vtkCylinderSource const &) = ::vtk_cylinder_source_get_radius;
  return vtk_cylinder_source_get_radius$(cylinder);
}

void cxxbridge1$192$vtk_cylinder_source_set_height(::vtkCylinderSource &cylinder, double height) noexcept {
  void (*vtk_cylinder_source_set_height$)(::vtkCylinderSource &, double) = ::vtk_cylinder_source_set_height;
  vtk_cylinder_source_set_height$(cylinder, height);
}

double cxxbridge1$192$vtk_cylinder_source_get_height(::vtkCylinderSource const &cylinder) noexcept {
  double (*vtk_cylinder_source_get_height$)(::vtkCylinderSource const &) = ::vtk_cylinder_source_get_height;
  return vtk_cylinder_source_get_height$(cylinder);
}

void cxxbridge1$192$vtk_cylinder_source_set_resolution(::vtkCylinderSource &cylinder, ::std::int32_t resolution) noexcept {
  void (*vtk_cylinder_source_set_resolution$)(::vtkCylinderSource &, ::std::int32_t) = ::vtk_cylinder_source_set_resolution;
  vtk_cylinder_source_set_resolution$(cylinder, resolution);
}

::std::int32_t cxxbridge1$192$vtk_cylinder_source_get_resolution(::vtkCylinderSource const &cylinder) noexcept {
  ::std::int32_t (*vtk_cylinder_source_get_resolution$)(::vtkCylinderSource const &) = ::vtk_cylinder_source_get_resolution;
  return vtk_cylinder_source_get_resolution$(cylinder);
}

void cxxbridge1$192$vtk_cylinder_source_set_center(::vtkCylinderSource &cylinder, double x, double y, double z) noexcept {
  void (*vtk_cylinder_source_set_center$)(::vtkCylinderSource &, double, double, double) = ::vtk_cylinder_source_set_center;
  vtk_cylinder_source_set_center$(cylinder, x, y, z);
}

void cxxbridge1$192$vtk_cylinder_source_get_center(::vtkCylinderSource const &cylinder, double &x, double &y, double &z) noexcept {
  void (*vtk_cylinder_source_get_center$)(::vtkCylinderSource const &, double &, double &, double &) = ::vtk_cylinder_source_get_center;
  vtk_cylinder_source_get_center$(cylinder, x, y, z);
}

void cxxbridge1$192$vtk_cylinder_source_set_capping(::vtkCylinderSource &cylinder, bool cap) noexcept {
  void (*vtk_cylinder_source_set_capping$)(::vtkCylinderSource &, bool) = ::vtk_cylinder_source_set_capping;
  vtk_cylinder_source_set_capping$(cylinder, cap);
}

bool cxxbridge1$192$vtk_cylinder_source_get_capping(::vtkCylinderSource const &cylinder) noexcept {
  bool (*vtk_cylinder_source_get_capping$)(::vtkCylinderSource const &) = ::vtk_cylinder_source_get_capping;
  return vtk_cylinder_source_get_capping$(cylinder);
}

::vtkAlgorithmOutput *cxxbridge1$192$vtk_cylinder_source_get_output_port(::vtkCylinderSource &cylinder) noexcept {
  ::vtkAlgorithmOutput *(*vtk_cylinder_source_get_output_port$)(::vtkCylinderSource &) = ::vtk_cylinder_source_get_output_port;
  return vtk_cylinder_source_get_output_port$(cylinder);
}
} // extern "C"