// AUTO-GENERATED BY cxxbridge
#include "vtk_orientation_marker_widget.h"
#include <cstdint>

#ifdef __GNUC__
#pragma GCC diagnostic ignored "-Wmissing-declarations"
#ifdef __clang__
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"
#endif // __clang__
#endif // __GNUC__

using vtkOrientationMarkerWidget = ::vtkOrientationMarkerWidget;
using vtkProp = ::vtkProp;
using vtkRenderWindowInteractor = ::vtkRenderWindowInteractor;

extern "C" {
::vtkOrientationMarkerWidget *cxxbridge1$192$orientation_marker_widget_new() noexcept {
  ::vtkOrientationMarkerWidget *(*orientation_marker_widget_new$)() = ::orientation_marker_widget_new;
  return orientation_marker_widget_new$();
}

void cxxbridge1$192$orientation_marker_widget_delete(::vtkOrientationMarkerWidget &widget) noexcept {
  void (*orientation_marker_widget_delete$)(::vtkOrientationMarkerWidget &) = ::orientation_marker_widget_delete;
  orientation_marker_widget_delete$(widget);
}

void cxxbridge1$192$orientation_marker_widget_set_orientation_marker(::vtkOrientationMarkerWidget &widget, ::vtkProp *marker) noexcept {
  void (*orientation_marker_widget_set_orientation_marker$)(::vtkOrientationMarkerWidget &, ::vtkProp *) = ::orientation_marker_widget_set_orientation_marker;
  orientation_marker_widget_set_orientation_marker$(widget, marker);
}

void cxxbridge1$192$orientation_marker_widget_set_interactor(::vtkOrientationMarkerWidget &widget, ::vtkRenderWindowInteractor *interactor) noexcept {
  void (*orientation_marker_widget_set_interactor$)(::vtkOrientationMarkerWidget &, ::vtkRenderWindowInteractor *) = ::orientation_marker_widget_set_interactor;
  orientation_marker_widget_set_interactor$(widget, interactor);
}

void cxxbridge1$192$orientation_marker_widget_set_viewport(::vtkOrientationMarkerWidget &widget, double min_x, double min_y, double max_x, double max_y) noexcept {
  void (*orientation_marker_widget_set_viewport$)(::vtkOrientationMarkerWidget &, double, double, double, double) = ::orientation_marker_widget_set_viewport;
  orientation_marker_widget_set_viewport$(widget, min_x, min_y, max_x, max_y);
}

void cxxbridge1$192$orientation_marker_widget_set_enabled(::vtkOrientationMarkerWidget &widget, ::std::int32_t enabled) noexcept {
  void (*orientation_marker_widget_set_enabled$)(::vtkOrientationMarkerWidget &, ::std::int32_t) = ::orientation_marker_widget_set_enabled;
  orientation_marker_widget_set_enabled$(widget, enabled);
}

void cxxbridge1$192$orientation_marker_widget_interactive_off(::vtkOrientationMarkerWidget &widget) noexcept {
  void (*orientation_marker_widget_interactive_off$)(::vtkOrientationMarkerWidget &) = ::orientation_marker_widget_interactive_off;
  orientation_marker_widget_interactive_off$(widget);
}
} // extern "C"