// AUTO-GENERATED BY cxxbridge
#include "vtk_command.h"
#include <cstddef>

#ifdef __GNUC__
#pragma GCC diagnostic ignored "-Wmissing-declarations"
#ifdef __clang__
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"
#endif // __clang__
#endif // __GNUC__

using RustCommand = ::RustCommand;
using vtkObject = ::vtkObject;

extern "C" {
::RustCommand *cxxbridge1$192$vtk_command_new() noexcept {
  ::RustCommand *(*vtk_command_new$)() = ::vtk_command_new;
  return vtk_command_new$();
}

void cxxbridge1$192$vtk_command_delete(::RustCommand *command) noexcept {
  void (*vtk_command_delete$)(::RustCommand *) = ::vtk_command_delete;
  vtk_command_delete$(command);
}

void cxxbridge1$192$vtk_command_set_callback(::RustCommand &command, ::std::size_t callback_fn, ::std::size_t user_data) noexcept {
  void (*vtk_command_set_callback$)(::RustCommand &, ::std::size_t, ::std::size_t) = ::vtk_command_set_callback;
  vtk_command_set_callback$(command, callback_fn, user_data);
}

::std::size_t cxxbridge1$192$vtk_object_add_observer(::vtkObject &obj, ::std::size_t event, ::RustCommand &command) noexcept {
  ::std::size_t (*vtk_object_add_observer$)(::vtkObject &, ::std::size_t, ::RustCommand &) = ::vtk_object_add_observer;
  return vtk_object_add_observer$(obj, event, command);
}

void cxxbridge1$192$vtk_object_remove_observer(::vtkObject &obj, ::std::size_t tag) noexcept {
  void (*vtk_object_remove_observer$)(::vtkObject &, ::std::size_t) = ::vtk_object_remove_observer;
  vtk_object_remove_observer$(obj, tag);
}
} // extern "C"