// AUTO-GENERATED BY cxxbridge
#include "vtk_interactor_style_trackball_camera.h"

#ifdef __GNUC__
#pragma GCC diagnostic ignored "-Wmissing-declarations"
#ifdef __clang__
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"
#endif // __clang__
#endif // __GNUC__

using vtkInteractorStyleTrackballCamera = ::vtkInteractorStyleTrackballCamera;

extern "C" {
::vtkInteractorStyleTrackballCamera *cxxbridge1$192$interactor_style_trackball_camera_new() noexcept {
  ::vtkInteractorStyleTrackballCamera *(*interactor_style_trackball_camera_new$)() = ::interactor_style_trackball_camera_new;
  return interactor_style_trackball_camera_new$();
}

void cxxbridge1$192$interactor_style_trackball_camera_delete(::vtkInteractorStyleTrackballCamera &style) noexcept {
  void (*interactor_style_trackball_camera_delete$)(::vtkInteractorStyleTrackballCamera &) = ::interactor_style_trackball_camera_delete;
  interactor_style_trackball_camera_delete$(style);
}
} // extern "C"