// AUTO-GENERATED BY cxxbridge
#include "vtk_arrow_source.h"
#include "vtk_algorithm_output.h"
#include <array>
#include <cstdint>
#include <new>
#include <string>

#ifdef __GNUC__
#pragma GCC diagnostic ignored "-Wmissing-declarations"
#ifdef __clang__
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"
#endif // __clang__
#endif // __GNUC__

namespace rust {
inline namespace cxxbridge1 {
// #include "rust/cxx.h"

struct unsafe_bitcopy_t;

#ifndef CXXBRIDGE1_RUST_STRING
#define CXXBRIDGE1_RUST_STRING
class String final {
public:
  String() noexcept;
  String(const String &) noexcept;
  String(String &&) noexcept;
  ~String() noexcept;

  String(const std::string &);
  String(const char *);
  String(const char *, std::size_t);
  String(const char16_t *);
  String(const char16_t *, std::size_t);
#ifdef __cpp_char8_t
  String(const char8_t *s);
  String(const char8_t *s, std::size_t len);
#endif

  static String lossy(const std::string &) noexcept;
  static String lossy(const char *) noexcept;
  static String lossy(const char *, std::size_t) noexcept;
  static String lossy(const char16_t *) noexcept;
  static String lossy(const char16_t *, std::size_t) noexcept;

  String &operator=(const String &) & noexcept;
  String &operator=(String &&) & noexcept;

  explicit operator std::string() const;

  const char *data() const noexcept;
  std::size_t size() const noexcept;
  std::size_t length() const noexcept;
  bool empty() const noexcept;

  const char *c_str() noexcept;

  std::size_t capacity() const noexcept;
  void reserve(size_t new_cap) noexcept;

  using iterator = char *;
  iterator begin() noexcept;
  iterator end() noexcept;

  using const_iterator = const char *;
  const_iterator begin() const noexcept;
  const_iterator end() const noexcept;
  const_iterator cbegin() const noexcept;
  const_iterator cend() const noexcept;

  bool operator==(const String &) const noexcept;
  bool operator!=(const String &) const noexcept;
  bool operator<(const String &) const noexcept;
  bool operator<=(const String &) const noexcept;
  bool operator>(const String &) const noexcept;
  bool operator>=(const String &) const noexcept;

  void swap(String &) noexcept;

  String(unsafe_bitcopy_t, const String &) noexcept;

private:
  struct lossy_t;
  String(lossy_t, const char *, std::size_t) noexcept;
  String(lossy_t, const char16_t *, std::size_t) noexcept;
  friend void swap(String &lhs, String &rhs) noexcept { lhs.swap(rhs); }

  std::array<std::uintptr_t, 3> repr;
};
#endif // CXXBRIDGE1_RUST_STRING
} // namespace cxxbridge1
} // namespace rust

using vtkArrowSource = ::vtkArrowSource;
using vtkAlgorithmOutput = ::vtkAlgorithmOutput;

extern "C" {
::vtkArrowSource *cxxbridge1$192$vtk_arrow_source_new() noexcept {
  ::vtkArrowSource *(*vtk_arrow_source_new$)() = ::vtk_arrow_source_new;
  return vtk_arrow_source_new$();
}

void cxxbridge1$192$vtk_arrow_source_delete(::vtkArrowSource &arrow) noexcept {
  void (*vtk_arrow_source_delete$)(::vtkArrowSource &) = ::vtk_arrow_source_delete;
  vtk_arrow_source_delete$(arrow);
}

void cxxbridge1$192$vtk_arrow_source_set_arrow_origin_to_default(::vtkArrowSource &arrow) noexcept {
  void (*vtk_arrow_source_set_arrow_origin_to_default$)(::vtkArrowSource &) = ::vtk_arrow_source_set_arrow_origin_to_default;
  vtk_arrow_source_set_arrow_origin_to_default$(arrow);
}

void cxxbridge1$192$vtk_arrow_source_set_arrow_origin_to_center(::vtkArrowSource &arrow) noexcept {
  void (*vtk_arrow_source_set_arrow_origin_to_center$)(::vtkArrowSource &) = ::vtk_arrow_source_set_arrow_origin_to_center;
  vtk_arrow_source_set_arrow_origin_to_center$(arrow);
}

void cxxbridge1$192$vtk_arrow_source_get_arrow_origin_as_string(::vtkArrowSource const &arrow, ::rust::String *return$) noexcept {
  ::rust::String (*vtk_arrow_source_get_arrow_origin_as_string$)(::vtkArrowSource const &) = ::vtk_arrow_source_get_arrow_origin_as_string;
  new (return$) ::rust::String(vtk_arrow_source_get_arrow_origin_as_string$(arrow));
}

void cxxbridge1$192$vtk_arrow_source_set_tip_length(::vtkArrowSource &arrow, double length) noexcept {
  void (*vtk_arrow_source_set_tip_length$)(::vtkArrowSource &, double) = ::vtk_arrow_source_set_tip_length;
  vtk_arrow_source_set_tip_length$(arrow, length);
}

double cxxbridge1$192$vtk_arrow_source_get_tip_length(::vtkArrowSource const &arrow) noexcept {
  double (*vtk_arrow_source_get_tip_length$)(::vtkArrowSource const &) = ::vtk_arrow_source_get_tip_length;
  return vtk_arrow_source_get_tip_length$(arrow);
}

void cxxbridge1$192$vtk_arrow_source_set_tip_radius(::vtkArrowSource &arrow, double radius) noexcept {
  void (*vtk_arrow_source_set_tip_radius$)(::vtkArrowSource &, double) = ::vtk_arrow_source_set_tip_radius;
  vtk_arrow_source_set_tip_radius$(arrow, radius);
}

double cxxbridge1$192$vtk_arrow_source_get_tip_radius(::vtkArrowSource const &arrow) noexcept {
  double (*vtk_arrow_source_get_tip_radius$)(::vtkArrowSource const &) = ::vtk_arrow_source_get_tip_radius;
  return vtk_arrow_source_get_tip_radius$(arrow);
}

void cxxbridge1$192$vtk_arrow_source_set_tip_resolution(::vtkArrowSource &arrow, ::std::int32_t res) noexcept {
  void (*vtk_arrow_source_set_tip_resolution$)(::vtkArrowSource &, ::std::int32_t) = ::vtk_arrow_source_set_tip_resolution;
  vtk_arrow_source_set_tip_resolution$(arrow, res);
}

::std::int32_t cxxbridge1$192$vtk_arrow_source_get_tip_resolution(::vtkArrowSource const &arrow) noexcept {
  ::std::int32_t (*vtk_arrow_source_get_tip_resolution$)(::vtkArrowSource const &) = ::vtk_arrow_source_get_tip_resolution;
  return vtk_arrow_source_get_tip_resolution$(arrow);
}

void cxxbridge1$192$vtk_arrow_source_set_shaft_radius(::vtkArrowSource &arrow, double radius) noexcept {
  void (*vtk_arrow_source_set_shaft_radius$)(::vtkArrowSource &, double) = ::vtk_arrow_source_set_shaft_radius;
  vtk_arrow_source_set_shaft_radius$(arrow, radius);
}

double cxxbridge1$192$vtk_arrow_source_get_shaft_radius(::vtkArrowSource const &arrow) noexcept {
  double (*vtk_arrow_source_get_shaft_radius$)(::vtkArrowSource const &) = ::vtk_arrow_source_get_shaft_radius;
  return vtk_arrow_source_get_shaft_radius$(arrow);
}

void cxxbridge1$192$vtk_arrow_source_set_shaft_resolution(::vtkArrowSource &arrow, ::std::int32_t res) noexcept {
  void (*vtk_arrow_source_set_shaft_resolution$)(::vtkArrowSource &, ::std::int32_t) = ::vtk_arrow_source_set_shaft_resolution;
  vtk_arrow_source_set_shaft_resolution$(arrow, res);
}

::std::int32_t cxxbridge1$192$vtk_arrow_source_get_shaft_resolution(::vtkArrowSource const &arrow) noexcept {
  ::std::int32_t (*vtk_arrow_source_get_shaft_resolution$)(::vtkArrowSource const &) = ::vtk_arrow_source_get_shaft_resolution;
  return vtk_arrow_source_get_shaft_resolution$(arrow);
}

void cxxbridge1$192$vtk_arrow_source_set_invert(::vtkArrowSource &arrow, bool invert) noexcept {
  void (*vtk_arrow_source_set_invert$)(::vtkArrowSource &, bool) = ::vtk_arrow_source_set_invert;
  vtk_arrow_source_set_invert$(arrow, invert);
}

void cxxbridge1$192$vtk_arrow_source_invert_on(::vtkArrowSource &arrow) noexcept {
  void (*vtk_arrow_source_invert_on$)(::vtkArrowSource &) = ::vtk_arrow_source_invert_on;
  vtk_arrow_source_invert_on$(arrow);
}

void cxxbridge1$192$vtk_arrow_source_invert_off(::vtkArrowSource &arrow) noexcept {
  void (*vtk_arrow_source_invert_off$)(::vtkArrowSource &) = ::vtk_arrow_source_invert_off;
  vtk_arrow_source_invert_off$(arrow);
}

bool cxxbridge1$192$vtk_arrow_source_get_invert(::vtkArrowSource const &arrow) noexcept {
  bool (*vtk_arrow_source_get_invert$)(::vtkArrowSource const &) = ::vtk_arrow_source_get_invert;
  return vtk_arrow_source_get_invert$(arrow);
}

::vtkAlgorithmOutput *cxxbridge1$192$vtk_arrow_source_get_output_port(::vtkArrowSource &arrow) noexcept {
  ::vtkAlgorithmOutput *(*vtk_arrow_source_get_output_port$)(::vtkArrowSource &) = ::vtk_arrow_source_get_output_port;
  return vtk_arrow_source_get_output_port$(arrow);
}
} // extern "C"