// AUTO-GENERATED BY cxxbridge
#include "vtk_prop_picker.h"
#include "vtk_renderer.h"

#ifdef __GNUC__
#pragma GCC diagnostic ignored "-Wmissing-declarations"
#ifdef __clang__
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"
#endif // __clang__
#endif // __GNUC__

using vtkPropPicker = ::vtkPropPicker;
using vtkRenderer = ::vtkRenderer;
using vtkProp = ::vtkProp;
using vtkActor = ::vtkActor;

extern "C" {
::vtkPropPicker *cxxbridge1$192$prop_picker_new() noexcept {
  ::vtkPropPicker *(*prop_picker_new$)() = ::prop_picker_new;
  return prop_picker_new$();
}

void cxxbridge1$192$prop_picker_delete(::vtkPropPicker &picker) noexcept {
  void (*prop_picker_delete$)(::vtkPropPicker &) = ::prop_picker_delete;
  prop_picker_delete$(picker);
}

bool cxxbridge1$192$prop_picker_pick(::vtkPropPicker &picker, double x, double y, double z, ::vtkRenderer *renderer) noexcept {
  bool (*prop_picker_pick$)(::vtkPropPicker &, double, double, double, ::vtkRenderer *) = ::prop_picker_pick;
  return prop_picker_pick$(picker, x, y, z, renderer);
}

void cxxbridge1$192$prop_picker_get_pick_position(::vtkPropPicker &picker, double &x, double &y, double &z) noexcept {
  void (*prop_picker_get_pick_position$)(::vtkPropPicker &, double &, double &, double &) = ::prop_picker_get_pick_position;
  prop_picker_get_pick_position$(picker, x, y, z);
}

::vtkProp *cxxbridge1$192$prop_picker_get_view_prop(::vtkPropPicker &picker) noexcept {
  ::vtkProp *(*prop_picker_get_view_prop$)(::vtkPropPicker &) = ::prop_picker_get_view_prop;
  return prop_picker_get_view_prop$(picker);
}

::vtkActor *cxxbridge1$192$prop_picker_get_actor(::vtkPropPicker &picker) noexcept {
  ::vtkActor *(*prop_picker_get_actor$)(::vtkPropPicker &) = ::prop_picker_get_actor;
  return prop_picker_get_actor$(picker);
}

void cxxbridge1$192$prop_picker_add_pick_list(::vtkPropPicker &picker, ::vtkProp *prop) noexcept {
  void (*prop_picker_add_pick_list$)(::vtkPropPicker &, ::vtkProp *) = ::prop_picker_add_pick_list;
  prop_picker_add_pick_list$(picker, prop);
}

void cxxbridge1$192$prop_picker_set_pick_from_list(::vtkPropPicker &picker, bool enabled) noexcept {
  void (*prop_picker_set_pick_from_list$)(::vtkPropPicker &, bool) = ::prop_picker_set_pick_from_list;
  prop_picker_set_pick_from_list$(picker, enabled);
}
} // extern "C"