// AUTO-GENERATED BY cxxbridge
#include "vtk_cell_picker.h"
#include "vtk_renderer.h"
#include <cstdint>

#ifdef __GNUC__
#pragma GCC diagnostic ignored "-Wmissing-declarations"
#ifdef __clang__
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"
#endif // __clang__
#endif // __GNUC__

using vtkCellPicker = ::vtkCellPicker;
using vtkRenderer = ::vtkRenderer;
using vtkActor = ::vtkActor;
using vtkDataSet = ::vtkDataSet;
using vtkProp3D = ::vtkProp3D;

extern "C" {
::vtkCellPicker *cxxbridge1$192$cell_picker_new() noexcept {
  ::vtkCellPicker *(*cell_picker_new$)() = ::cell_picker_new;
  return cell_picker_new$();
}

void cxxbridge1$192$cell_picker_delete(::vtkCellPicker &picker) noexcept {
  void (*cell_picker_delete$)(::vtkCellPicker &) = ::cell_picker_delete;
  cell_picker_delete$(picker);
}

bool cxxbridge1$192$cell_picker_pick(::vtkCellPicker &picker, double x, double y, double z, ::vtkRenderer *renderer) noexcept {
  bool (*cell_picker_pick$)(::vtkCellPicker &, double, double, double, ::vtkRenderer *) = ::cell_picker_pick;
  return cell_picker_pick$(picker, x, y, z, renderer);
}

::std::int32_t cxxbridge1$192$cell_picker_get_cell_id(::vtkCellPicker &picker) noexcept {
  ::std::int32_t (*cell_picker_get_cell_id$)(::vtkCellPicker &) = ::cell_picker_get_cell_id;
  return cell_picker_get_cell_id$(picker);
}

::vtkDataSet *cxxbridge1$192$cell_picker_get_dataset(::vtkCellPicker &picker) noexcept {
  ::vtkDataSet *(*cell_picker_get_dataset$)(::vtkCellPicker &) = ::cell_picker_get_dataset;
  return cell_picker_get_dataset$(picker);
}

void cxxbridge1$192$cell_picker_get_pick_position(::vtkCellPicker &picker, double &x, double &y, double &z) noexcept {
  void (*cell_picker_get_pick_position$)(::vtkCellPicker &, double &, double &, double &) = ::cell_picker_get_pick_position;
  cell_picker_get_pick_position$(picker, x, y, z);
}

::vtkActor *cxxbridge1$192$cell_picker_get_actor(::vtkCellPicker &picker) noexcept {
  ::vtkActor *(*cell_picker_get_actor$)(::vtkCellPicker &) = ::cell_picker_get_actor;
  return cell_picker_get_actor$(picker);
}

void cxxbridge1$192$cell_picker_add_pick_list(::vtkCellPicker &picker, ::vtkProp3D *prop) noexcept {
  void (*cell_picker_add_pick_list$)(::vtkCellPicker &, ::vtkProp3D *) = ::cell_picker_add_pick_list;
  cell_picker_add_pick_list$(picker, prop);
}

void cxxbridge1$192$cell_picker_set_pick_from_list(::vtkCellPicker &picker, bool enabled) noexcept {
  void (*cell_picker_set_pick_from_list$)(::vtkCellPicker &, bool) = ::cell_picker_set_pick_from_list;
  cell_picker_set_pick_from_list$(picker, enabled);
}

void cxxbridge1$192$cell_picker_set_tolerance(::vtkCellPicker &picker, double tolerance) noexcept {
  void (*cell_picker_set_tolerance$)(::vtkCellPicker &, double) = ::cell_picker_set_tolerance;
  cell_picker_set_tolerance$(picker, tolerance);
}
} // extern "C"