// AUTO-GENERATED BY cxxbridge
#include "vtk_vector_text.h"
#include <array>
#include <cstdint>
#include <new>
#include <string>

#ifdef __GNUC__
#pragma GCC diagnostic ignored "-Wmissing-declarations"
#ifdef __clang__
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"
#endif // __clang__
#endif // __GNUC__

namespace rust {
inline namespace cxxbridge1 {
// #include "rust/cxx.h"

struct unsafe_bitcopy_t;

#ifndef CXXBRIDGE1_RUST_STRING
#define CXXBRIDGE1_RUST_STRING
class String final {
public:
  String() noexcept;
  String(const String &) noexcept;
  String(String &&) noexcept;
  ~String() noexcept;

  String(const std::string &);
  String(const char *);
  String(const char *, std::size_t);
  String(const char16_t *);
  String(const char16_t *, std::size_t);
#ifdef __cpp_char8_t
  String(const char8_t *s);
  String(const char8_t *s, std::size_t len);
#endif

  static String lossy(const std::string &) noexcept;
  static String lossy(const char *) noexcept;
  static String lossy(const char *, std::size_t) noexcept;
  static String lossy(const char16_t *) noexcept;
  static String lossy(const char16_t *, std::size_t) noexcept;

  String &operator=(const String &) & noexcept;
  String &operator=(String &&) & noexcept;

  explicit operator std::string() const;

  const char *data() const noexcept;
  std::size_t size() const noexcept;
  std::size_t length() const noexcept;
  bool empty() const noexcept;

  const char *c_str() noexcept;

  std::size_t capacity() const noexcept;
  void reserve(size_t new_cap) noexcept;

  using iterator = char *;
  iterator begin() noexcept;
  iterator end() noexcept;

  using const_iterator = const char *;
  const_iterator begin() const noexcept;
  const_iterator end() const noexcept;
  const_iterator cbegin() const noexcept;
  const_iterator cend() const noexcept;

  bool operator==(const String &) const noexcept;
  bool operator!=(const String &) const noexcept;
  bool operator<(const String &) const noexcept;
  bool operator<=(const String &) const noexcept;
  bool operator>(const String &) const noexcept;
  bool operator>=(const String &) const noexcept;

  void swap(String &) noexcept;

  String(unsafe_bitcopy_t, const String &) noexcept;

private:
  struct lossy_t;
  String(lossy_t, const char *, std::size_t) noexcept;
  String(lossy_t, const char16_t *, std::size_t) noexcept;
  friend void swap(String &lhs, String &rhs) noexcept { lhs.swap(rhs); }

  std::array<std::uintptr_t, 3> repr;
};
#endif // CXXBRIDGE1_RUST_STRING

#ifndef CXXBRIDGE1_RUST_BITCOPY_T
#define CXXBRIDGE1_RUST_BITCOPY_T
struct unsafe_bitcopy_t final {
  explicit unsafe_bitcopy_t() = default;
};
#endif // CXXBRIDGE1_RUST_BITCOPY_T

#ifndef CXXBRIDGE1_RUST_BITCOPY
#define CXXBRIDGE1_RUST_BITCOPY
constexpr unsafe_bitcopy_t unsafe_bitcopy{};
#endif // CXXBRIDGE1_RUST_BITCOPY
} // namespace cxxbridge1
} // namespace rust

using vtkVectorText = ::vtkVectorText;
using vtkAlgorithmOutput = ::vtkAlgorithmOutput;

extern "C" {
::vtkVectorText *cxxbridge1$192$vtk_vector_text_new() noexcept {
  ::vtkVectorText *(*vtk_vector_text_new$)() = ::vtk_vector_text_new;
  return vtk_vector_text_new$();
}

void cxxbridge1$192$vtk_vector_text_delete(::vtkVectorText &ptr) noexcept {
  void (*vtk_vector_text_delete$)(::vtkVectorText &) = ::vtk_vector_text_delete;
  vtk_vector_text_delete$(ptr);
}

void cxxbridge1$192$vector_text_set_text(::vtkVectorText &source, ::rust::String const *text) noexcept {
  void (*vector_text_set_text$)(::vtkVectorText &, ::rust::String) = ::vector_text_set_text;
  vector_text_set_text$(source, ::rust::String(::rust::unsafe_bitcopy, *text));
}

void cxxbridge1$192$vector_text_get_text(::vtkVectorText &source, ::rust::String *return$) noexcept {
  ::rust::String (*vector_text_get_text$)(::vtkVectorText &) = ::vector_text_get_text;
  new (return$) ::rust::String(vector_text_get_text$(source));
}

::vtkAlgorithmOutput *cxxbridge1$192$vector_text_get_output_port(::vtkVectorText &source) noexcept {
  ::vtkAlgorithmOutput *(*vector_text_get_output_port$)(::vtkVectorText &) = ::vector_text_get_output_port;
  return vector_text_get_output_port$(source);
}
} // extern "C"