// AUTO-GENERATED BY cxxbridge
#include "vtk_parametric_klein.h"
#include "vtk_parametric_function.h"

#ifdef __GNUC__
#pragma GCC diagnostic ignored "-Wmissing-declarations"
#ifdef __clang__
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"
#endif // __clang__
#endif // __GNUC__

using vtkParametricKlein = ::vtkParametricKlein;
using vtkParametricFunction = ::vtkParametricFunction;

extern "C" {
::vtkParametricKlein *cxxbridge1$192$vtk_parametric_klein_new() noexcept {
  ::vtkParametricKlein *(*vtk_parametric_klein_new$)() = ::vtk_parametric_klein_new;
  return vtk_parametric_klein_new$();
}

void cxxbridge1$192$vtk_parametric_klein_delete(::vtkParametricKlein &ptr) noexcept {
  void (*vtk_parametric_klein_delete$)(::vtkParametricKlein &) = ::vtk_parametric_klein_delete;
  vtk_parametric_klein_delete$(ptr);
}

::vtkParametricFunction *cxxbridge1$192$parametric_klein_as_parametric_function(::vtkParametricKlein &klein) noexcept {
  ::vtkParametricFunction *(*parametric_klein_as_parametric_function$)(::vtkParametricKlein &) = ::parametric_klein_as_parametric_function;
  return parametric_klein_as_parametric_function$(klein);
}
} // extern "C"