// AUTO-GENERATED BY cxxbridge
#include "vtk_point_picker.h"
#include "vtk_renderer.h"
#include <cstdint>

#ifdef __GNUC__
#pragma GCC diagnostic ignored "-Wmissing-declarations"
#ifdef __clang__
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"
#endif // __clang__
#endif // __GNUC__

using vtkPointPicker = ::vtkPointPicker;
using vtkRenderer = ::vtkRenderer;

extern "C" {
::vtkPointPicker *cxxbridge1$192$vtk_point_picker_new() noexcept {
  ::vtkPointPicker *(*vtk_point_picker_new$)() = ::vtk_point_picker_new;
  return vtk_point_picker_new$();
}

void cxxbridge1$192$vtk_point_picker_delete(::vtkPointPicker &picker) noexcept {
  void (*vtk_point_picker_delete$)(::vtkPointPicker &) = ::vtk_point_picker_delete;
  vtk_point_picker_delete$(picker);
}

::std::int32_t cxxbridge1$192$vtk_point_picker_pick(::vtkPointPicker &picker, double x, double y, double z, ::vtkRenderer *renderer) noexcept {
  ::std::int32_t (*vtk_point_picker_pick$)(::vtkPointPicker &, double, double, double, ::vtkRenderer *) = ::vtk_point_picker_pick;
  return vtk_point_picker_pick$(picker, x, y, z, renderer);
}

::std::int32_t cxxbridge1$192$vtk_point_picker_get_point_id(::vtkPointPicker &picker) noexcept {
  ::std::int32_t (*vtk_point_picker_get_point_id$)(::vtkPointPicker &) = ::vtk_point_picker_get_point_id;
  return vtk_point_picker_get_point_id$(picker);
}

void cxxbridge1$192$vtk_point_picker_get_pick_position(::vtkPointPicker &picker, double &x, double &y, double &z) noexcept {
  void (*vtk_point_picker_get_pick_position$)(::vtkPointPicker &, double &, double &, double &) = ::vtk_point_picker_get_pick_position;
  vtk_point_picker_get_pick_position$(picker, x, y, z);
}
} // extern "C"