// AUTO-GENERATED BY cxxbridge
#include "vtk_area_picker.h"
#include "vtk_renderer.h"
#include <cstdint>

#ifdef __GNUC__
#pragma GCC diagnostic ignored "-Wmissing-declarations"
#ifdef __clang__
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"
#endif // __clang__
#endif // __GNUC__

using vtkAreaPicker = ::vtkAreaPicker;
using vtkRenderer = ::vtkRenderer;
using vtkProp3DCollection = ::vtkProp3DCollection;

extern "C" {
::vtkAreaPicker *cxxbridge1$192$vtk_area_picker_new() noexcept {
  ::vtkAreaPicker *(*vtk_area_picker_new$)() = ::vtk_area_picker_new;
  return vtk_area_picker_new$();
}

void cxxbridge1$192$vtk_area_picker_delete(::vtkAreaPicker &picker) noexcept {
  void (*vtk_area_picker_delete$)(::vtkAreaPicker &) = ::vtk_area_picker_delete;
  vtk_area_picker_delete$(picker);
}

::std::int32_t cxxbridge1$192$vtk_area_picker_area_pick(::vtkAreaPicker &picker, double x0, double y0, double x1, double y1, ::vtkRenderer *renderer) noexcept {
  ::std::int32_t (*vtk_area_picker_area_pick$)(::vtkAreaPicker &, double, double, double, double, ::vtkRenderer *) = ::vtk_area_picker_area_pick;
  return vtk_area_picker_area_pick$(picker, x0, y0, x1, y1, renderer);
}

::vtkProp3DCollection *cxxbridge1$192$vtk_area_picker_get_prop3ds(::vtkAreaPicker &picker) noexcept {
  ::vtkProp3DCollection *(*vtk_area_picker_get_prop3ds$)(::vtkAreaPicker &) = ::vtk_area_picker_get_prop3ds;
  return vtk_area_picker_get_prop3ds$(picker);
}
} // extern "C"