// AUTO-GENERATED BY cxxbridge
#include "vtk_unstructured_grid.h"
#include "vtk_points.h"
#include <cstdint>

#ifdef __GNUC__
#pragma GCC diagnostic ignored "-Wmissing-declarations"
#ifdef __clang__
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"
#endif // __clang__
#endif // __GNUC__

using vtkUnstructuredGrid = ::vtkUnstructuredGrid;
using vtkPoints = ::vtkPoints;

extern "C" {
::vtkUnstructuredGrid *cxxbridge1$192$vtk_unstructured_grid_new() noexcept {
  ::vtkUnstructuredGrid *(*vtk_unstructured_grid_new$)() = ::vtk_unstructured_grid_new;
  return vtk_unstructured_grid_new$();
}

void cxxbridge1$192$vtk_unstructured_grid_delete(::vtkUnstructuredGrid &grid) noexcept {
  void (*vtk_unstructured_grid_delete$)(::vtkUnstructuredGrid &) = ::vtk_unstructured_grid_delete;
  vtk_unstructured_grid_delete$(grid);
}

void cxxbridge1$192$unstructured_grid_set_points(::vtkUnstructuredGrid &grid, ::vtkPoints *points) noexcept {
  void (*unstructured_grid_set_points$)(::vtkUnstructuredGrid &, ::vtkPoints *) = ::unstructured_grid_set_points;
  unstructured_grid_set_points$(grid, points);
}

::vtkPoints *cxxbridge1$192$unstructured_grid_get_points(::vtkUnstructuredGrid &grid) noexcept {
  ::vtkPoints *(*unstructured_grid_get_points$)(::vtkUnstructuredGrid &) = ::unstructured_grid_get_points;
  return unstructured_grid_get_points$(grid);
}

void cxxbridge1$192$unstructured_grid_allocate(::vtkUnstructuredGrid &grid, ::std::int32_t num_cells) noexcept {
  void (*unstructured_grid_allocate$)(::vtkUnstructuredGrid &, ::std::int32_t) = ::unstructured_grid_allocate;
  unstructured_grid_allocate$(grid, num_cells);
}

void cxxbridge1$192$unstructured_grid_insert_next_cell(::vtkUnstructuredGrid &grid, ::std::int32_t cell_type, ::std::int32_t num_points, ::std::int32_t const *point_ids) noexcept {
  void (*unstructured_grid_insert_next_cell$)(::vtkUnstructuredGrid &, ::std::int32_t, ::std::int32_t, ::std::int32_t const *) = ::unstructured_grid_insert_next_cell;
  unstructured_grid_insert_next_cell$(grid, cell_type, num_points, point_ids);
}

::std::int32_t cxxbridge1$192$unstructured_grid_get_number_of_points(::vtkUnstructuredGrid const &grid) noexcept {
  ::std::int32_t (*unstructured_grid_get_number_of_points$)(::vtkUnstructuredGrid const &) = ::unstructured_grid_get_number_of_points;
  return unstructured_grid_get_number_of_points$(grid);
}

::std::int32_t cxxbridge1$192$unstructured_grid_get_number_of_cells(::vtkUnstructuredGrid const &grid) noexcept {
  ::std::int32_t (*unstructured_grid_get_number_of_cells$)(::vtkUnstructuredGrid const &) = ::unstructured_grid_get_number_of_cells;
  return unstructured_grid_get_number_of_cells$(grid);
}

void cxxbridge1$192$unstructured_grid_get_bounds(::vtkUnstructuredGrid const &grid, double *bounds) noexcept {
  void (*unstructured_grid_get_bounds$)(::vtkUnstructuredGrid const &, double *) = ::unstructured_grid_get_bounds;
  unstructured_grid_get_bounds$(grid, bounds);
}
} // extern "C"