// AUTO-GENERATED BY cxxbridge
#include "vtk_cube_axes_actor.h"
#include <array>
#include <cstdint>
#include <string>
#if __cplusplus >= 201703L
#include <string_view>
#endif

#ifdef __GNUC__
#pragma GCC diagnostic ignored "-Wmissing-declarations"
#ifdef __clang__
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"
#endif // __clang__
#endif // __GNUC__

namespace rust {
inline namespace cxxbridge1 {
// #include "rust/cxx.h"

namespace {
template <typename T>
class impl;
} // namespace

class String;

#ifndef CXXBRIDGE1_RUST_STR
#define CXXBRIDGE1_RUST_STR
class Str final {
public:
  Str() noexcept;
  Str(const String &) noexcept;
  Str(const std::string &);
  Str(const char *);
  Str(const char *, std::size_t);

  Str &operator=(const Str &) & noexcept = default;

  explicit operator std::string() const;
#if __cplusplus >= 201703L
  explicit operator std::string_view() const;
#endif

  const char *data() const noexcept;
  std::size_t size() const noexcept;
  std::size_t length() const noexcept;
  bool empty() const noexcept;

  Str(const Str &) noexcept = default;
  ~Str() noexcept = default;

  using iterator = const char *;
  using const_iterator = const char *;
  const_iterator begin() const noexcept;
  const_iterator end() const noexcept;
  const_iterator cbegin() const noexcept;
  const_iterator cend() const noexcept;

  bool operator==(const Str &) const noexcept;
  bool operator!=(const Str &) const noexcept;
  bool operator<(const Str &) const noexcept;
  bool operator<=(const Str &) const noexcept;
  bool operator>(const Str &) const noexcept;
  bool operator>=(const Str &) const noexcept;

  void swap(Str &) noexcept;

private:
  class uninit;
  Str(uninit) noexcept;
  friend impl<Str>;

  std::array<std::uintptr_t, 2> repr;
};
#endif // CXXBRIDGE1_RUST_STR
} // namespace cxxbridge1
} // namespace rust

using vtkCubeAxesActor = ::vtkCubeAxesActor;
using vtkCamera = ::vtkCamera;

extern "C" {
::vtkCubeAxesActor *cxxbridge1$192$cube_axes_actor_new() noexcept {
  ::vtkCubeAxesActor *(*cube_axes_actor_new$)() = ::cube_axes_actor_new;
  return cube_axes_actor_new$();
}

void cxxbridge1$192$cube_axes_actor_delete(::vtkCubeAxesActor &actor) noexcept {
  void (*cube_axes_actor_delete$)(::vtkCubeAxesActor &) = ::cube_axes_actor_delete;
  cube_axes_actor_delete$(actor);
}

void cxxbridge1$192$cube_axes_actor_set_bounds(::vtkCubeAxesActor &actor, double x_min, double x_max, double y_min, double y_max, double z_min, double z_max) noexcept {
  void (*cube_axes_actor_set_bounds$)(::vtkCubeAxesActor &, double, double, double, double, double, double) = ::cube_axes_actor_set_bounds;
  cube_axes_actor_set_bounds$(actor, x_min, x_max, y_min, y_max, z_min, z_max);
}

void cxxbridge1$192$cube_axes_actor_set_camera(::vtkCubeAxesActor &actor, ::vtkCamera *camera) noexcept {
  void (*cube_axes_actor_set_camera$)(::vtkCubeAxesActor &, ::vtkCamera *) = ::cube_axes_actor_set_camera;
  cube_axes_actor_set_camera$(actor, camera);
}

void cxxbridge1$192$cube_axes_actor_set_x_label(::vtkCubeAxesActor &actor, ::rust::Str label) noexcept {
  void (*cube_axes_actor_set_x_label$)(::vtkCubeAxesActor &, ::rust::Str) = ::cube_axes_actor_set_x_label;
  cube_axes_actor_set_x_label$(actor, label);
}

void cxxbridge1$192$cube_axes_actor_set_y_label(::vtkCubeAxesActor &actor, ::rust::Str label) noexcept {
  void (*cube_axes_actor_set_y_label$)(::vtkCubeAxesActor &, ::rust::Str) = ::cube_axes_actor_set_y_label;
  cube_axes_actor_set_y_label$(actor, label);
}

void cxxbridge1$192$cube_axes_actor_set_z_label(::vtkCubeAxesActor &actor, ::rust::Str label) noexcept {
  void (*cube_axes_actor_set_z_label$)(::vtkCubeAxesActor &, ::rust::Str) = ::cube_axes_actor_set_z_label;
  cube_axes_actor_set_z_label$(actor, label);
}

void cxxbridge1$192$cube_axes_actor_draw_x_gridlines_on(::vtkCubeAxesActor &actor) noexcept {
  void (*cube_axes_actor_draw_x_gridlines_on$)(::vtkCubeAxesActor &) = ::cube_axes_actor_draw_x_gridlines_on;
  cube_axes_actor_draw_x_gridlines_on$(actor);
}

void cxxbridge1$192$cube_axes_actor_draw_y_gridlines_on(::vtkCubeAxesActor &actor) noexcept {
  void (*cube_axes_actor_draw_y_gridlines_on$)(::vtkCubeAxesActor &) = ::cube_axes_actor_draw_y_gridlines_on;
  cube_axes_actor_draw_y_gridlines_on$(actor);
}

void cxxbridge1$192$cube_axes_actor_draw_z_gridlines_on(::vtkCubeAxesActor &actor) noexcept {
  void (*cube_axes_actor_draw_z_gridlines_on$)(::vtkCubeAxesActor &) = ::cube_axes_actor_draw_z_gridlines_on;
  cube_axes_actor_draw_z_gridlines_on$(actor);
}
} // extern "C"