// AUTO-GENERATED BY cxxbridge
#include "vtk_cone_source.h"
#include "vtk_algorithm_output.h"
#include <cstdint>

#ifdef __GNUC__
#pragma GCC diagnostic ignored "-Wmissing-declarations"
#ifdef __clang__
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"
#endif // __clang__
#endif // __GNUC__

using vtkConeSource = ::vtkConeSource;
using vtkAlgorithmOutput = ::vtkAlgorithmOutput;

extern "C" {
::vtkConeSource *cxxbridge1$192$vtk_cone_source_new() noexcept {
  ::vtkConeSource *(*vtk_cone_source_new$)() = ::vtk_cone_source_new;
  return vtk_cone_source_new$();
}

void cxxbridge1$192$vtk_cone_source_delete(::vtkConeSource &cone) noexcept {
  void (*vtk_cone_source_delete$)(::vtkConeSource &) = ::vtk_cone_source_delete;
  vtk_cone_source_delete$(cone);
}

void cxxbridge1$192$vtk_cone_source_set_radius(::vtkConeSource &cone, double radius) noexcept {
  void (*vtk_cone_source_set_radius$)(::vtkConeSource &, double) = ::vtk_cone_source_set_radius;
  vtk_cone_source_set_radius$(cone, radius);
}

double cxxbridge1$192$vtk_cone_source_get_radius(::vtkConeSource const &cone) noexcept {
  double (*vtk_cone_source_get_radius$)(::vtkConeSource const &) = ::vtk_cone_source_get_radius;
  return vtk_cone_source_get_radius$(cone);
}

void cxxbridge1$192$vtk_cone_source_set_height(::vtkConeSource &cone, double height) noexcept {
  void (*vtk_cone_source_set_height$)(::vtkConeSource &, double) = ::vtk_cone_source_set_height;
  vtk_cone_source_set_height$(cone, height);
}

double cxxbridge1$192$vtk_cone_source_get_height(::vtkConeSource const &cone) noexcept {
  double (*vtk_cone_source_get_height$)(::vtkConeSource const &) = ::vtk_cone_source_get_height;
  return vtk_cone_source_get_height$(cone);
}

void cxxbridge1$192$vtk_cone_source_set_resolution(::vtkConeSource &cone, ::std::int32_t resolution) noexcept {
  void (*vtk_cone_source_set_resolution$)(::vtkConeSource &, ::std::int32_t) = ::vtk_cone_source_set_resolution;
  vtk_cone_source_set_resolution$(cone, resolution);
}

::std::int32_t cxxbridge1$192$vtk_cone_source_get_resolution(::vtkConeSource const &cone) noexcept {
  ::std::int32_t (*vtk_cone_source_get_resolution$)(::vtkConeSource const &) = ::vtk_cone_source_get_resolution;
  return vtk_cone_source_get_resolution$(cone);
}

void cxxbridge1$192$vtk_cone_source_set_direction(::vtkConeSource &cone, double x, double y, double z) noexcept {
  void (*vtk_cone_source_set_direction$)(::vtkConeSource &, double, double, double) = ::vtk_cone_source_set_direction;
  vtk_cone_source_set_direction$(cone, x, y, z);
}

void cxxbridge1$192$vtk_cone_source_get_direction(::vtkConeSource const &cone, double &x, double &y, double &z) noexcept {
  void (*vtk_cone_source_get_direction$)(::vtkConeSource const &, double &, double &, double &) = ::vtk_cone_source_get_direction;
  vtk_cone_source_get_direction$(cone, x, y, z);
}

void cxxbridge1$192$vtk_cone_source_set_center(::vtkConeSource &cone, double x, double y, double z) noexcept {
  void (*vtk_cone_source_set_center$)(::vtkConeSource &, double, double, double) = ::vtk_cone_source_set_center;
  vtk_cone_source_set_center$(cone, x, y, z);
}

void cxxbridge1$192$vtk_cone_source_get_center(::vtkConeSource const &cone, double &x, double &y, double &z) noexcept {
  void (*vtk_cone_source_get_center$)(::vtkConeSource const &, double &, double &, double &) = ::vtk_cone_source_get_center;
  vtk_cone_source_get_center$(cone, x, y, z);
}

void cxxbridge1$192$vtk_cone_source_set_capping(::vtkConeSource &cone, bool cap) noexcept {
  void (*vtk_cone_source_set_capping$)(::vtkConeSource &, bool) = ::vtk_cone_source_set_capping;
  vtk_cone_source_set_capping$(cone, cap);
}

bool cxxbridge1$192$vtk_cone_source_get_capping(::vtkConeSource const &cone) noexcept {
  bool (*vtk_cone_source_get_capping$)(::vtkConeSource const &) = ::vtk_cone_source_get_capping;
  return vtk_cone_source_get_capping$(cone);
}

void cxxbridge1$192$vtk_cone_source_set_angle(::vtkConeSource &cone, double angle) noexcept {
  void (*vtk_cone_source_set_angle$)(::vtkConeSource &, double) = ::vtk_cone_source_set_angle;
  vtk_cone_source_set_angle$(cone, angle);
}

double cxxbridge1$192$vtk_cone_source_get_angle(::vtkConeSource const &cone) noexcept {
  double (*vtk_cone_source_get_angle$)(::vtkConeSource const &) = ::vtk_cone_source_get_angle;
  return vtk_cone_source_get_angle$(cone);
}

::vtkAlgorithmOutput *cxxbridge1$192$vtk_cone_source_get_output_port(::vtkConeSource &cone) noexcept {
  ::vtkAlgorithmOutput *(*vtk_cone_source_get_output_port$)(::vtkConeSource &) = ::vtk_cone_source_get_output_port;
  return vtk_cone_source_get_output_port$(cone);
}
} // extern "C"