// AUTO-GENERATED BY cxxbridge
#include "vtk_regular_polygon_source.h"
#include "vtk_algorithm_output.h"
#include <cstdint>

#ifdef __GNUC__
#pragma GCC diagnostic ignored "-Wmissing-declarations"
#ifdef __clang__
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"
#endif // __clang__
#endif // __GNUC__

using vtkRegularPolygonSource = ::vtkRegularPolygonSource;
using vtkAlgorithmOutput = ::vtkAlgorithmOutput;

extern "C" {
::vtkRegularPolygonSource *cxxbridge1$192$vtk_regular_polygon_source_new() noexcept {
  ::vtkRegularPolygonSource *(*vtk_regular_polygon_source_new$)() = ::vtk_regular_polygon_source_new;
  return vtk_regular_polygon_source_new$();
}

void cxxbridge1$192$vtk_regular_polygon_source_delete(::vtkRegularPolygonSource &polygon) noexcept {
  void (*vtk_regular_polygon_source_delete$)(::vtkRegularPolygonSource &) = ::vtk_regular_polygon_source_delete;
  vtk_regular_polygon_source_delete$(polygon);
}

void cxxbridge1$192$vtk_regular_polygon_source_set_number_of_sides(::vtkRegularPolygonSource &polygon, ::std::int32_t sides) noexcept {
  void (*vtk_regular_polygon_source_set_number_of_sides$)(::vtkRegularPolygonSource &, ::std::int32_t) = ::vtk_regular_polygon_source_set_number_of_sides;
  vtk_regular_polygon_source_set_number_of_sides$(polygon, sides);
}

::std::int32_t cxxbridge1$192$vtk_regular_polygon_source_get_number_of_sides(::vtkRegularPolygonSource const &polygon) noexcept {
  ::std::int32_t (*vtk_regular_polygon_source_get_number_of_sides$)(::vtkRegularPolygonSource const &) = ::vtk_regular_polygon_source_get_number_of_sides;
  return vtk_regular_polygon_source_get_number_of_sides$(polygon);
}

void cxxbridge1$192$vtk_regular_polygon_source_set_center(::vtkRegularPolygonSource &polygon, double x, double y, double z) noexcept {
  void (*vtk_regular_polygon_source_set_center$)(::vtkRegularPolygonSource &, double, double, double) = ::vtk_regular_polygon_source_set_center;
  vtk_regular_polygon_source_set_center$(polygon, x, y, z);
}

void cxxbridge1$192$vtk_regular_polygon_source_get_center(::vtkRegularPolygonSource const &polygon, double &x, double &y, double &z) noexcept {
  void (*vtk_regular_polygon_source_get_center$)(::vtkRegularPolygonSource const &, double &, double &, double &) = ::vtk_regular_polygon_source_get_center;
  vtk_regular_polygon_source_get_center$(polygon, x, y, z);
}

void cxxbridge1$192$vtk_regular_polygon_source_set_normal(::vtkRegularPolygonSource &polygon, double x, double y, double z) noexcept {
  void (*vtk_regular_polygon_source_set_normal$)(::vtkRegularPolygonSource &, double, double, double) = ::vtk_regular_polygon_source_set_normal;
  vtk_regular_polygon_source_set_normal$(polygon, x, y, z);
}

void cxxbridge1$192$vtk_regular_polygon_source_get_normal(::vtkRegularPolygonSource const &polygon, double &x, double &y, double &z) noexcept {
  void (*vtk_regular_polygon_source_get_normal$)(::vtkRegularPolygonSource const &, double &, double &, double &) = ::vtk_regular_polygon_source_get_normal;
  vtk_regular_polygon_source_get_normal$(polygon, x, y, z);
}

void cxxbridge1$192$vtk_regular_polygon_source_set_radius(::vtkRegularPolygonSource &polygon, double radius) noexcept {
  void (*vtk_regular_polygon_source_set_radius$)(::vtkRegularPolygonSource &, double) = ::vtk_regular_polygon_source_set_radius;
  vtk_regular_polygon_source_set_radius$(polygon, radius);
}

double cxxbridge1$192$vtk_regular_polygon_source_get_radius(::vtkRegularPolygonSource const &polygon) noexcept {
  double (*vtk_regular_polygon_source_get_radius$)(::vtkRegularPolygonSource const &) = ::vtk_regular_polygon_source_get_radius;
  return vtk_regular_polygon_source_get_radius$(polygon);
}

void cxxbridge1$192$vtk_regular_polygon_source_set_generate_polygon(::vtkRegularPolygonSource &polygon, bool generate) noexcept {
  void (*vtk_regular_polygon_source_set_generate_polygon$)(::vtkRegularPolygonSource &, bool) = ::vtk_regular_polygon_source_set_generate_polygon;
  vtk_regular_polygon_source_set_generate_polygon$(polygon, generate);
}

bool cxxbridge1$192$vtk_regular_polygon_source_get_generate_polygon(::vtkRegularPolygonSource const &polygon) noexcept {
  bool (*vtk_regular_polygon_source_get_generate_polygon$)(::vtkRegularPolygonSource const &) = ::vtk_regular_polygon_source_get_generate_polygon;
  return vtk_regular_polygon_source_get_generate_polygon$(polygon);
}

void cxxbridge1$192$vtk_regular_polygon_source_generate_polygon_on(::vtkRegularPolygonSource &polygon) noexcept {
  void (*vtk_regular_polygon_source_generate_polygon_on$)(::vtkRegularPolygonSource &) = ::vtk_regular_polygon_source_generate_polygon_on;
  vtk_regular_polygon_source_generate_polygon_on$(polygon);
}

void cxxbridge1$192$vtk_regular_polygon_source_generate_polygon_off(::vtkRegularPolygonSource &polygon) noexcept {
  void (*vtk_regular_polygon_source_generate_polygon_off$)(::vtkRegularPolygonSource &) = ::vtk_regular_polygon_source_generate_polygon_off;
  vtk_regular_polygon_source_generate_polygon_off$(polygon);
}

void cxxbridge1$192$vtk_regular_polygon_source_set_generate_polyline(::vtkRegularPolygonSource &polygon, bool generate) noexcept {
  void (*vtk_regular_polygon_source_set_generate_polyline$)(::vtkRegularPolygonSource &, bool) = ::vtk_regular_polygon_source_set_generate_polyline;
  vtk_regular_polygon_source_set_generate_polyline$(polygon, generate);
}

bool cxxbridge1$192$vtk_regular_polygon_source_get_generate_polyline(::vtkRegularPolygonSource const &polygon) noexcept {
  bool (*vtk_regular_polygon_source_get_generate_polyline$)(::vtkRegularPolygonSource const &) = ::vtk_regular_polygon_source_get_generate_polyline;
  return vtk_regular_polygon_source_get_generate_polyline$(polygon);
}

void cxxbridge1$192$vtk_regular_polygon_source_generate_polyline_on(::vtkRegularPolygonSource &polygon) noexcept {
  void (*vtk_regular_polygon_source_generate_polyline_on$)(::vtkRegularPolygonSource &) = ::vtk_regular_polygon_source_generate_polyline_on;
  vtk_regular_polygon_source_generate_polyline_on$(polygon);
}

void cxxbridge1$192$vtk_regular_polygon_source_generate_polyline_off(::vtkRegularPolygonSource &polygon) noexcept {
  void (*vtk_regular_polygon_source_generate_polyline_off$)(::vtkRegularPolygonSource &) = ::vtk_regular_polygon_source_generate_polyline_off;
  vtk_regular_polygon_source_generate_polyline_off$(polygon);
}

void cxxbridge1$192$vtk_regular_polygon_source_set_output_points_precision(::vtkRegularPolygonSource &polygon, ::std::int32_t precision) noexcept {
  void (*vtk_regular_polygon_source_set_output_points_precision$)(::vtkRegularPolygonSource &, ::std::int32_t) = ::vtk_regular_polygon_source_set_output_points_precision;
  vtk_regular_polygon_source_set_output_points_precision$(polygon, precision);
}

::std::int32_t cxxbridge1$192$vtk_regular_polygon_source_get_output_points_precision(::vtkRegularPolygonSource const &polygon) noexcept {
  ::std::int32_t (*vtk_regular_polygon_source_get_output_points_precision$)(::vtkRegularPolygonSource const &) = ::vtk_regular_polygon_source_get_output_points_precision;
  return vtk_regular_polygon_source_get_output_points_precision$(polygon);
}

::vtkAlgorithmOutput *cxxbridge1$192$vtk_regular_polygon_source_get_output_port(::vtkRegularPolygonSource &polygon) noexcept {
  ::vtkAlgorithmOutput *(*vtk_regular_polygon_source_get_output_port$)(::vtkRegularPolygonSource &) = ::vtk_regular_polygon_source_get_output_port;
  return vtk_regular_polygon_source_get_output_port$(polygon);
}
} // extern "C"