// AUTO-GENERATED BY cxxbridge
#include "vtk_follower.h"
#include <cstddef>

#ifdef __GNUC__
#pragma GCC diagnostic ignored "-Wmissing-declarations"
#ifdef __clang__
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"
#endif // __clang__
#endif // __GNUC__

using vtkFollower = ::vtkFollower;

extern "C" {
::vtkFollower *cxxbridge1$192$vtk_follower_new() noexcept {
  ::vtkFollower *(*vtk_follower_new$)() = ::vtk_follower_new;
  return vtk_follower_new$();
}

void cxxbridge1$192$vtk_follower_delete(::vtkFollower &ptr) noexcept {
  void (*vtk_follower_delete$)(::vtkFollower &) = ::vtk_follower_delete;
  vtk_follower_delete$(ptr);
}

void cxxbridge1$192$follower_set_camera(::vtkFollower &follower, ::std::size_t camera) noexcept {
  void (*follower_set_camera$)(::vtkFollower &, ::std::size_t) = ::follower_set_camera;
  follower_set_camera$(follower, camera);
}

void cxxbridge1$192$follower_set_mapper(::vtkFollower &follower, ::std::size_t mapper) noexcept {
  void (*follower_set_mapper$)(::vtkFollower &, ::std::size_t) = ::follower_set_mapper;
  follower_set_mapper$(follower, mapper);
}

void cxxbridge1$192$follower_set_position(::vtkFollower &follower, double x, double y, double z) noexcept {
  void (*follower_set_position$)(::vtkFollower &, double, double, double) = ::follower_set_position;
  follower_set_position$(follower, x, y, z);
}

void cxxbridge1$192$follower_get_position(::vtkFollower &follower, double &x, double &y, double &z) noexcept {
  void (*follower_get_position$)(::vtkFollower &, double &, double &, double &) = ::follower_get_position;
  follower_get_position$(follower, x, y, z);
}

void cxxbridge1$192$follower_set_scale(::vtkFollower &follower, double x, double y, double z) noexcept {
  void (*follower_set_scale$)(::vtkFollower &, double, double, double) = ::follower_set_scale;
  follower_set_scale$(follower, x, y, z);
}

void cxxbridge1$192$follower_get_scale(::vtkFollower &follower, double &x, double &y, double &z) noexcept {
  void (*follower_get_scale$)(::vtkFollower &, double &, double &, double &) = ::follower_get_scale;
  follower_get_scale$(follower, x, y, z);
}
} // extern "C"