// AUTO-GENERATED BY cxxbridge
#include "vtk_property.h"
#include <cstdint>

#ifdef __GNUC__
#pragma GCC diagnostic ignored "-Wmissing-declarations"
#ifdef __clang__
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"
#endif // __clang__
#endif // __GNUC__

using vtkProperty = ::vtkProperty;

extern "C" {
::vtkProperty *cxxbridge1$192$property_new() noexcept {
  ::vtkProperty *(*property_new$)() = ::property_new;
  return property_new$();
}

void cxxbridge1$192$property_delete(::vtkProperty &property) noexcept {
  void (*property_delete$)(::vtkProperty &) = ::property_delete;
  property_delete$(property);
}

void cxxbridge1$192$property_set_color(::vtkProperty &property, double r, double g, double b) noexcept {
  void (*property_set_color$)(::vtkProperty &, double, double, double) = ::property_set_color;
  property_set_color$(property, r, g, b);
}

void cxxbridge1$192$property_get_color(::vtkProperty &property, double &r, double &g, double &b) noexcept {
  void (*property_get_color$)(::vtkProperty &, double &, double &, double &) = ::property_get_color;
  property_get_color$(property, r, g, b);
}

void cxxbridge1$192$property_set_opacity(::vtkProperty &property, double opacity) noexcept {
  void (*property_set_opacity$)(::vtkProperty &, double) = ::property_set_opacity;
  property_set_opacity$(property, opacity);
}

double cxxbridge1$192$property_get_opacity(::vtkProperty &property) noexcept {
  double (*property_get_opacity$)(::vtkProperty &) = ::property_get_opacity;
  return property_get_opacity$(property);
}

void cxxbridge1$192$property_set_line_width(::vtkProperty &property, double width) noexcept {
  void (*property_set_line_width$)(::vtkProperty &, double) = ::property_set_line_width;
  property_set_line_width$(property, width);
}

double cxxbridge1$192$property_get_line_width(::vtkProperty &property) noexcept {
  double (*property_get_line_width$)(::vtkProperty &) = ::property_get_line_width;
  return property_get_line_width$(property);
}

void cxxbridge1$192$property_set_point_size(::vtkProperty &property, double size) noexcept {
  void (*property_set_point_size$)(::vtkProperty &, double) = ::property_set_point_size;
  property_set_point_size$(property, size);
}

double cxxbridge1$192$property_get_point_size(::vtkProperty &property) noexcept {
  double (*property_get_point_size$)(::vtkProperty &) = ::property_get_point_size;
  return property_get_point_size$(property);
}

void cxxbridge1$192$property_set_representation(::vtkProperty &property, ::std::int32_t representation) noexcept {
  void (*property_set_representation$)(::vtkProperty &, ::std::int32_t) = ::property_set_representation;
  property_set_representation$(property, representation);
}

::std::int32_t cxxbridge1$192$property_get_representation(::vtkProperty &property) noexcept {
  ::std::int32_t (*property_get_representation$)(::vtkProperty &) = ::property_get_representation;
  return property_get_representation$(property);
}

void cxxbridge1$192$property_set_edge_visibility(::vtkProperty &property, bool visible) noexcept {
  void (*property_set_edge_visibility$)(::vtkProperty &, bool) = ::property_set_edge_visibility;
  property_set_edge_visibility$(property, visible);
}

bool cxxbridge1$192$property_get_edge_visibility(::vtkProperty &property) noexcept {
  bool (*property_get_edge_visibility$)(::vtkProperty &) = ::property_get_edge_visibility;
  return property_get_edge_visibility$(property);
}

void cxxbridge1$192$property_set_edge_color(::vtkProperty &property, double r, double g, double b) noexcept {
  void (*property_set_edge_color$)(::vtkProperty &, double, double, double) = ::property_set_edge_color;
  property_set_edge_color$(property, r, g, b);
}

void cxxbridge1$192$property_get_edge_color(::vtkProperty &property, double &r, double &g, double &b) noexcept {
  void (*property_get_edge_color$)(::vtkProperty &, double &, double &, double &) = ::property_get_edge_color;
  property_get_edge_color$(property, r, g, b);
}

void cxxbridge1$192$property_set_interpolation(::vtkProperty &property, ::std::int32_t interpolation) noexcept {
  void (*property_set_interpolation$)(::vtkProperty &, ::std::int32_t) = ::property_set_interpolation;
  property_set_interpolation$(property, interpolation);
}

::std::int32_t cxxbridge1$192$property_get_interpolation(::vtkProperty &property) noexcept {
  ::std::int32_t (*property_get_interpolation$)(::vtkProperty &) = ::property_get_interpolation;
  return property_get_interpolation$(property);
}

void cxxbridge1$192$property_set_ambient(::vtkProperty &property, double ambient) noexcept {
  void (*property_set_ambient$)(::vtkProperty &, double) = ::property_set_ambient;
  property_set_ambient$(property, ambient);
}

double cxxbridge1$192$property_get_ambient(::vtkProperty &property) noexcept {
  double (*property_get_ambient$)(::vtkProperty &) = ::property_get_ambient;
  return property_get_ambient$(property);
}

void cxxbridge1$192$property_set_diffuse(::vtkProperty &property, double diffuse) noexcept {
  void (*property_set_diffuse$)(::vtkProperty &, double) = ::property_set_diffuse;
  property_set_diffuse$(property, diffuse);
}

double cxxbridge1$192$property_get_diffuse(::vtkProperty &property) noexcept {
  double (*property_get_diffuse$)(::vtkProperty &) = ::property_get_diffuse;
  return property_get_diffuse$(property);
}

void cxxbridge1$192$property_set_specular(::vtkProperty &property, double specular) noexcept {
  void (*property_set_specular$)(::vtkProperty &, double) = ::property_set_specular;
  property_set_specular$(property, specular);
}

double cxxbridge1$192$property_get_specular(::vtkProperty &property) noexcept {
  double (*property_get_specular$)(::vtkProperty &) = ::property_get_specular;
  return property_get_specular$(property);
}

void cxxbridge1$192$property_set_specular_power(::vtkProperty &property, double power) noexcept {
  void (*property_set_specular_power$)(::vtkProperty &, double) = ::property_set_specular_power;
  property_set_specular_power$(property, power);
}

double cxxbridge1$192$property_get_specular_power(::vtkProperty &property) noexcept {
  double (*property_get_specular_power$)(::vtkProperty &) = ::property_get_specular_power;
  return property_get_specular_power$(property);
}
} // extern "C"