// AUTO-GENERATED BY cxxbridge
#include "vtk_parametric_torus.h"
#include "vtk_parametric_function.h"

#ifdef __GNUC__
#pragma GCC diagnostic ignored "-Wmissing-declarations"
#ifdef __clang__
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"
#endif // __clang__
#endif // __GNUC__

using vtkParametricTorus = ::vtkParametricTorus;
using vtkParametricFunction = ::vtkParametricFunction;

extern "C" {
::vtkParametricTorus *cxxbridge1$192$vtk_parametric_torus_new() noexcept {
  ::vtkParametricTorus *(*vtk_parametric_torus_new$)() = ::vtk_parametric_torus_new;
  return vtk_parametric_torus_new$();
}

void cxxbridge1$192$vtk_parametric_torus_delete(::vtkParametricTorus &ptr) noexcept {
  void (*vtk_parametric_torus_delete$)(::vtkParametricTorus &) = ::vtk_parametric_torus_delete;
  vtk_parametric_torus_delete$(ptr);
}

void cxxbridge1$192$parametric_torus_set_ring_radius(::vtkParametricTorus &torus, double radius) noexcept {
  void (*parametric_torus_set_ring_radius$)(::vtkParametricTorus &, double) = ::parametric_torus_set_ring_radius;
  parametric_torus_set_ring_radius$(torus, radius);
}

double cxxbridge1$192$parametric_torus_get_ring_radius(::vtkParametricTorus const &torus) noexcept {
  double (*parametric_torus_get_ring_radius$)(::vtkParametricTorus const &) = ::parametric_torus_get_ring_radius;
  return parametric_torus_get_ring_radius$(torus);
}

void cxxbridge1$192$parametric_torus_set_cross_section_radius(::vtkParametricTorus &torus, double radius) noexcept {
  void (*parametric_torus_set_cross_section_radius$)(::vtkParametricTorus &, double) = ::parametric_torus_set_cross_section_radius;
  parametric_torus_set_cross_section_radius$(torus, radius);
}

double cxxbridge1$192$parametric_torus_get_cross_section_radius(::vtkParametricTorus const &torus) noexcept {
  double (*parametric_torus_get_cross_section_radius$)(::vtkParametricTorus const &) = ::parametric_torus_get_cross_section_radius;
  return parametric_torus_get_cross_section_radius$(torus);
}

::vtkParametricFunction *cxxbridge1$192$parametric_torus_as_parametric_function(::vtkParametricTorus &torus) noexcept {
  ::vtkParametricFunction *(*parametric_torus_as_parametric_function$)(::vtkParametricTorus &) = ::parametric_torus_as_parametric_function;
  return parametric_torus_as_parametric_function$(torus);
}
} // extern "C"