// AUTO-GENERATED BY cxxbridge
#include "vtk_parametric_function_source.h"
#include "vtk_algorithm_output.h"
#include "vtk_parametric_function.h"
#include <cstdint>

#ifdef __GNUC__
#pragma GCC diagnostic ignored "-Wmissing-declarations"
#ifdef __clang__
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"
#endif // __clang__
#endif // __GNUC__

using vtkParametricFunctionSource = ::vtkParametricFunctionSource;
using vtkAlgorithmOutput = ::vtkAlgorithmOutput;
using vtkParametricFunction = ::vtkParametricFunction;

extern "C" {
::vtkParametricFunctionSource *cxxbridge1$192$vtk_parametric_function_source_new() noexcept {
  ::vtkParametricFunctionSource *(*vtk_parametric_function_source_new$)() = ::vtk_parametric_function_source_new;
  return vtk_parametric_function_source_new$();
}

void cxxbridge1$192$vtk_parametric_function_source_delete(::vtkParametricFunctionSource &ptr) noexcept {
  void (*vtk_parametric_function_source_delete$)(::vtkParametricFunctionSource &) = ::vtk_parametric_function_source_delete;
  vtk_parametric_function_source_delete$(ptr);
}

void cxxbridge1$192$parametric_function_source_set_parametric_function(::vtkParametricFunctionSource &source, ::vtkParametricFunction *func) noexcept {
  void (*parametric_function_source_set_parametric_function$)(::vtkParametricFunctionSource &, ::vtkParametricFunction *) = ::parametric_function_source_set_parametric_function;
  parametric_function_source_set_parametric_function$(source, func);
}

void cxxbridge1$192$parametric_function_source_set_u_resolution(::vtkParametricFunctionSource &source, ::std::int32_t resolution) noexcept {
  void (*parametric_function_source_set_u_resolution$)(::vtkParametricFunctionSource &, ::std::int32_t) = ::parametric_function_source_set_u_resolution;
  parametric_function_source_set_u_resolution$(source, resolution);
}

::std::int32_t cxxbridge1$192$parametric_function_source_get_u_resolution(::vtkParametricFunctionSource const &source) noexcept {
  ::std::int32_t (*parametric_function_source_get_u_resolution$)(::vtkParametricFunctionSource const &) = ::parametric_function_source_get_u_resolution;
  return parametric_function_source_get_u_resolution$(source);
}

void cxxbridge1$192$parametric_function_source_set_v_resolution(::vtkParametricFunctionSource &source, ::std::int32_t resolution) noexcept {
  void (*parametric_function_source_set_v_resolution$)(::vtkParametricFunctionSource &, ::std::int32_t) = ::parametric_function_source_set_v_resolution;
  parametric_function_source_set_v_resolution$(source, resolution);
}

::std::int32_t cxxbridge1$192$parametric_function_source_get_v_resolution(::vtkParametricFunctionSource const &source) noexcept {
  ::std::int32_t (*parametric_function_source_get_v_resolution$)(::vtkParametricFunctionSource const &) = ::parametric_function_source_get_v_resolution;
  return parametric_function_source_get_v_resolution$(source);
}

void cxxbridge1$192$parametric_function_source_set_w_resolution(::vtkParametricFunctionSource &source, ::std::int32_t resolution) noexcept {
  void (*parametric_function_source_set_w_resolution$)(::vtkParametricFunctionSource &, ::std::int32_t) = ::parametric_function_source_set_w_resolution;
  parametric_function_source_set_w_resolution$(source, resolution);
}

::std::int32_t cxxbridge1$192$parametric_function_source_get_w_resolution(::vtkParametricFunctionSource const &source) noexcept {
  ::std::int32_t (*parametric_function_source_get_w_resolution$)(::vtkParametricFunctionSource const &) = ::parametric_function_source_get_w_resolution;
  return parametric_function_source_get_w_resolution$(source);
}

::vtkAlgorithmOutput *cxxbridge1$192$parametric_function_source_get_output_port(::vtkParametricFunctionSource &source) noexcept {
  ::vtkAlgorithmOutput *(*parametric_function_source_get_output_port$)(::vtkParametricFunctionSource &) = ::parametric_function_source_get_output_port;
  return parametric_function_source_get_output_port$(source);
}
} // extern "C"