// AUTO-GENERATED BY cxxbridge
#include "vtk_poly_data_mapper.h"
#include "vtk_algorithm_output.h"
#include "vtk_mapper.h"

#ifdef __GNUC__
#pragma GCC diagnostic ignored "-Wmissing-declarations"
#ifdef __clang__
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"
#endif // __clang__
#endif // __GNUC__

using vtkPolyDataMapper = ::vtkPolyDataMapper;
using vtkAlgorithmOutput = ::vtkAlgorithmOutput;
using vtkMapper = ::vtkMapper;

extern "C" {
::vtkPolyDataMapper *cxxbridge1$192$poly_data_mapper_new() noexcept {
  ::vtkPolyDataMapper *(*poly_data_mapper_new$)() = ::poly_data_mapper_new;
  return poly_data_mapper_new$();
}

void cxxbridge1$192$poly_data_mapper_delete(::vtkPolyDataMapper &pdm) noexcept {
  void (*poly_data_mapper_delete$)(::vtkPolyDataMapper &) = ::poly_data_mapper_delete;
  poly_data_mapper_delete$(pdm);
}

void cxxbridge1$192$poly_data_mapper_set_input_connection(::vtkPolyDataMapper &mapper, ::vtkAlgorithmOutput *output) noexcept {
  void (*poly_data_mapper_set_input_connection$)(::vtkPolyDataMapper &, ::vtkAlgorithmOutput *) = ::poly_data_mapper_set_input_connection;
  poly_data_mapper_set_input_connection$(mapper, output);
}
} // extern "C"