// AUTO-GENERATED BY cxxbridge
#include "vtk_superquadric_source.h"
#include "vtk_algorithm_output.h"
#include <cstdint>

#ifdef __GNUC__
#pragma GCC diagnostic ignored "-Wmissing-declarations"
#ifdef __clang__
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"
#endif // __clang__
#endif // __GNUC__

using vtkSuperquadricSource = ::vtkSuperquadricSource;
using vtkAlgorithmOutput = ::vtkAlgorithmOutput;

extern "C" {
::vtkSuperquadricSource *cxxbridge1$192$vtk_superquadric_source_new() noexcept {
  ::vtkSuperquadricSource *(*vtk_superquadric_source_new$)() = ::vtk_superquadric_source_new;
  return vtk_superquadric_source_new$();
}

void cxxbridge1$192$vtk_superquadric_source_delete(::vtkSuperquadricSource &ptr) noexcept {
  void (*vtk_superquadric_source_delete$)(::vtkSuperquadricSource &) = ::vtk_superquadric_source_delete;
  vtk_superquadric_source_delete$(ptr);
}

void cxxbridge1$192$superquadric_source_set_center(::vtkSuperquadricSource &source, double x, double y, double z) noexcept {
  void (*superquadric_source_set_center$)(::vtkSuperquadricSource &, double, double, double) = ::superquadric_source_set_center;
  superquadric_source_set_center$(source, x, y, z);
}

void cxxbridge1$192$superquadric_source_get_center(::vtkSuperquadricSource &source, double &x, double &y, double &z) noexcept {
  void (*superquadric_source_get_center$)(::vtkSuperquadricSource &, double &, double &, double &) = ::superquadric_source_get_center;
  superquadric_source_get_center$(source, x, y, z);
}

void cxxbridge1$192$superquadric_source_set_scale(::vtkSuperquadricSource &source, double x, double y, double z) noexcept {
  void (*superquadric_source_set_scale$)(::vtkSuperquadricSource &, double, double, double) = ::superquadric_source_set_scale;
  superquadric_source_set_scale$(source, x, y, z);
}

void cxxbridge1$192$superquadric_source_get_scale(::vtkSuperquadricSource &source, double &x, double &y, double &z) noexcept {
  void (*superquadric_source_get_scale$)(::vtkSuperquadricSource &, double &, double &, double &) = ::superquadric_source_get_scale;
  superquadric_source_get_scale$(source, x, y, z);
}

void cxxbridge1$192$superquadric_source_set_size(::vtkSuperquadricSource &source, double size) noexcept {
  void (*superquadric_source_set_size$)(::vtkSuperquadricSource &, double) = ::superquadric_source_set_size;
  superquadric_source_set_size$(source, size);
}

double cxxbridge1$192$superquadric_source_get_size(::vtkSuperquadricSource &source) noexcept {
  double (*superquadric_source_get_size$)(::vtkSuperquadricSource &) = ::superquadric_source_get_size;
  return superquadric_source_get_size$(source);
}

void cxxbridge1$192$superquadric_source_set_theta_roundness(::vtkSuperquadricSource &source, double roundness) noexcept {
  void (*superquadric_source_set_theta_roundness$)(::vtkSuperquadricSource &, double) = ::superquadric_source_set_theta_roundness;
  superquadric_source_set_theta_roundness$(source, roundness);
}

double cxxbridge1$192$superquadric_source_get_theta_roundness(::vtkSuperquadricSource &source) noexcept {
  double (*superquadric_source_get_theta_roundness$)(::vtkSuperquadricSource &) = ::superquadric_source_get_theta_roundness;
  return superquadric_source_get_theta_roundness$(source);
}

void cxxbridge1$192$superquadric_source_set_phi_roundness(::vtkSuperquadricSource &source, double roundness) noexcept {
  void (*superquadric_source_set_phi_roundness$)(::vtkSuperquadricSource &, double) = ::superquadric_source_set_phi_roundness;
  superquadric_source_set_phi_roundness$(source, roundness);
}

double cxxbridge1$192$superquadric_source_get_phi_roundness(::vtkSuperquadricSource &source) noexcept {
  double (*superquadric_source_get_phi_roundness$)(::vtkSuperquadricSource &) = ::superquadric_source_get_phi_roundness;
  return superquadric_source_get_phi_roundness$(source);
}

void cxxbridge1$192$superquadric_source_set_thickness(::vtkSuperquadricSource &source, double thickness) noexcept {
  void (*superquadric_source_set_thickness$)(::vtkSuperquadricSource &, double) = ::superquadric_source_set_thickness;
  superquadric_source_set_thickness$(source, thickness);
}

double cxxbridge1$192$superquadric_source_get_thickness(::vtkSuperquadricSource &source) noexcept {
  double (*superquadric_source_get_thickness$)(::vtkSuperquadricSource &) = ::superquadric_source_get_thickness;
  return superquadric_source_get_thickness$(source);
}

void cxxbridge1$192$superquadric_source_set_toroidal(::vtkSuperquadricSource &source, bool toroidal) noexcept {
  void (*superquadric_source_set_toroidal$)(::vtkSuperquadricSource &, bool) = ::superquadric_source_set_toroidal;
  superquadric_source_set_toroidal$(source, toroidal);
}

bool cxxbridge1$192$superquadric_source_get_toroidal(::vtkSuperquadricSource &source) noexcept {
  bool (*superquadric_source_get_toroidal$)(::vtkSuperquadricSource &) = ::superquadric_source_get_toroidal;
  return superquadric_source_get_toroidal$(source);
}

void cxxbridge1$192$superquadric_source_toroidal_on(::vtkSuperquadricSource &source) noexcept {
  void (*superquadric_source_toroidal_on$)(::vtkSuperquadricSource &) = ::superquadric_source_toroidal_on;
  superquadric_source_toroidal_on$(source);
}

void cxxbridge1$192$superquadric_source_toroidal_off(::vtkSuperquadricSource &source) noexcept {
  void (*superquadric_source_toroidal_off$)(::vtkSuperquadricSource &) = ::superquadric_source_toroidal_off;
  superquadric_source_toroidal_off$(source);
}

void cxxbridge1$192$superquadric_source_set_theta_resolution(::vtkSuperquadricSource &source, ::std::int32_t resolution) noexcept {
  void (*superquadric_source_set_theta_resolution$)(::vtkSuperquadricSource &, ::std::int32_t) = ::superquadric_source_set_theta_resolution;
  superquadric_source_set_theta_resolution$(source, resolution);
}

::std::int32_t cxxbridge1$192$superquadric_source_get_theta_resolution(::vtkSuperquadricSource &source) noexcept {
  ::std::int32_t (*superquadric_source_get_theta_resolution$)(::vtkSuperquadricSource &) = ::superquadric_source_get_theta_resolution;
  return superquadric_source_get_theta_resolution$(source);
}

void cxxbridge1$192$superquadric_source_set_phi_resolution(::vtkSuperquadricSource &source, ::std::int32_t resolution) noexcept {
  void (*superquadric_source_set_phi_resolution$)(::vtkSuperquadricSource &, ::std::int32_t) = ::superquadric_source_set_phi_resolution;
  superquadric_source_set_phi_resolution$(source, resolution);
}

::std::int32_t cxxbridge1$192$superquadric_source_get_phi_resolution(::vtkSuperquadricSource &source) noexcept {
  ::std::int32_t (*superquadric_source_get_phi_resolution$)(::vtkSuperquadricSource &) = ::superquadric_source_get_phi_resolution;
  return superquadric_source_get_phi_resolution$(source);
}

::vtkAlgorithmOutput *cxxbridge1$192$superquadric_source_get_output_port(::vtkSuperquadricSource &source) noexcept {
  ::vtkAlgorithmOutput *(*superquadric_source_get_output_port$)(::vtkSuperquadricSource &) = ::superquadric_source_get_output_port;
  return superquadric_source_get_output_port$(source);
}
} // extern "C"