// AUTO-GENERATED BY cxxbridge
#include "vtk_plane_source.h"
#include "vtk_algorithm_output.h"
#include <cstdint>

#ifdef __GNUC__
#pragma GCC diagnostic ignored "-Wmissing-declarations"
#ifdef __clang__
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"
#endif // __clang__
#endif // __GNUC__

using vtkPlaneSource = ::vtkPlaneSource;
using vtkAlgorithmOutput = ::vtkAlgorithmOutput;

extern "C" {
::vtkPlaneSource *cxxbridge1$192$vtk_plane_source_new() noexcept {
  ::vtkPlaneSource *(*vtk_plane_source_new$)() = ::vtk_plane_source_new;
  return vtk_plane_source_new$();
}

void cxxbridge1$192$vtk_plane_source_delete(::vtkPlaneSource &plane) noexcept {
  void (*vtk_plane_source_delete$)(::vtkPlaneSource &) = ::vtk_plane_source_delete;
  vtk_plane_source_delete$(plane);
}

void cxxbridge1$192$vtk_plane_source_set_origin(::vtkPlaneSource &plane, double x, double y, double z) noexcept {
  void (*vtk_plane_source_set_origin$)(::vtkPlaneSource &, double, double, double) = ::vtk_plane_source_set_origin;
  vtk_plane_source_set_origin$(plane, x, y, z);
}

void cxxbridge1$192$vtk_plane_source_get_origin(::vtkPlaneSource const &plane, double &x, double &y, double &z) noexcept {
  void (*vtk_plane_source_get_origin$)(::vtkPlaneSource const &, double &, double &, double &) = ::vtk_plane_source_get_origin;
  vtk_plane_source_get_origin$(plane, x, y, z);
}

void cxxbridge1$192$vtk_plane_source_set_point1(::vtkPlaneSource &plane, double x, double y, double z) noexcept {
  void (*vtk_plane_source_set_point1$)(::vtkPlaneSource &, double, double, double) = ::vtk_plane_source_set_point1;
  vtk_plane_source_set_point1$(plane, x, y, z);
}

void cxxbridge1$192$vtk_plane_source_get_point1(::vtkPlaneSource const &plane, double &x, double &y, double &z) noexcept {
  void (*vtk_plane_source_get_point1$)(::vtkPlaneSource const &, double &, double &, double &) = ::vtk_plane_source_get_point1;
  vtk_plane_source_get_point1$(plane, x, y, z);
}

void cxxbridge1$192$vtk_plane_source_set_point2(::vtkPlaneSource &plane, double x, double y, double z) noexcept {
  void (*vtk_plane_source_set_point2$)(::vtkPlaneSource &, double, double, double) = ::vtk_plane_source_set_point2;
  vtk_plane_source_set_point2$(plane, x, y, z);
}

void cxxbridge1$192$vtk_plane_source_get_point2(::vtkPlaneSource const &plane, double &x, double &y, double &z) noexcept {
  void (*vtk_plane_source_get_point2$)(::vtkPlaneSource const &, double &, double &, double &) = ::vtk_plane_source_get_point2;
  vtk_plane_source_get_point2$(plane, x, y, z);
}

void cxxbridge1$192$vtk_plane_source_set_x_resolution(::vtkPlaneSource &plane, ::std::int32_t r) noexcept {
  void (*vtk_plane_source_set_x_resolution$)(::vtkPlaneSource &, ::std::int32_t) = ::vtk_plane_source_set_x_resolution;
  vtk_plane_source_set_x_resolution$(plane, r);
}

::std::int32_t cxxbridge1$192$vtk_plane_source_get_x_resolution(::vtkPlaneSource const &plane) noexcept {
  ::std::int32_t (*vtk_plane_source_get_x_resolution$)(::vtkPlaneSource const &) = ::vtk_plane_source_get_x_resolution;
  return vtk_plane_source_get_x_resolution$(plane);
}

void cxxbridge1$192$vtk_plane_source_set_y_resolution(::vtkPlaneSource &plane, ::std::int32_t r) noexcept {
  void (*vtk_plane_source_set_y_resolution$)(::vtkPlaneSource &, ::std::int32_t) = ::vtk_plane_source_set_y_resolution;
  vtk_plane_source_set_y_resolution$(plane, r);
}

::std::int32_t cxxbridge1$192$vtk_plane_source_get_y_resolution(::vtkPlaneSource const &plane) noexcept {
  ::std::int32_t (*vtk_plane_source_get_y_resolution$)(::vtkPlaneSource const &) = ::vtk_plane_source_get_y_resolution;
  return vtk_plane_source_get_y_resolution$(plane);
}

void cxxbridge1$192$vtk_plane_source_set_center(::vtkPlaneSource &plane, double x, double y, double z) noexcept {
  void (*vtk_plane_source_set_center$)(::vtkPlaneSource &, double, double, double) = ::vtk_plane_source_set_center;
  vtk_plane_source_set_center$(plane, x, y, z);
}

void cxxbridge1$192$vtk_plane_source_set_normal(::vtkPlaneSource &plane, double x, double y, double z) noexcept {
  void (*vtk_plane_source_set_normal$)(::vtkPlaneSource &, double, double, double) = ::vtk_plane_source_set_normal;
  vtk_plane_source_set_normal$(plane, x, y, z);
}

void cxxbridge1$192$vtk_plane_source_push(::vtkPlaneSource &plane, double distance) noexcept {
  void (*vtk_plane_source_push$)(::vtkPlaneSource &, double) = ::vtk_plane_source_push;
  vtk_plane_source_push$(plane, distance);
}

::vtkAlgorithmOutput *cxxbridge1$192$vtk_plane_source_get_output_port(::vtkPlaneSource &plane) noexcept {
  ::vtkAlgorithmOutput *(*vtk_plane_source_get_output_port$)(::vtkPlaneSource &) = ::vtk_plane_source_get_output_port;
  return vtk_plane_source_get_output_port$(plane);
}
} // extern "C"