// AUTO-GENERATED BY cxxbridge
#include "vtk_disk_source.h"
#include "vtk_algorithm_output.h"
#include <cstdint>

#ifdef __GNUC__
#pragma GCC diagnostic ignored "-Wmissing-declarations"
#ifdef __clang__
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"
#endif // __clang__
#endif // __GNUC__

using vtkDiskSource = ::vtkDiskSource;
using vtkAlgorithmOutput = ::vtkAlgorithmOutput;

extern "C" {
::vtkDiskSource *cxxbridge1$192$vtk_disk_source_new() noexcept {
  ::vtkDiskSource *(*vtk_disk_source_new$)() = ::vtk_disk_source_new;
  return vtk_disk_source_new$();
}

void cxxbridge1$192$vtk_disk_source_delete(::vtkDiskSource &disk) noexcept {
  void (*vtk_disk_source_delete$)(::vtkDiskSource &) = ::vtk_disk_source_delete;
  vtk_disk_source_delete$(disk);
}

void cxxbridge1$192$vtk_disk_source_set_inner_radius(::vtkDiskSource &disk, double radius) noexcept {
  void (*vtk_disk_source_set_inner_radius$)(::vtkDiskSource &, double) = ::vtk_disk_source_set_inner_radius;
  vtk_disk_source_set_inner_radius$(disk, radius);
}

double cxxbridge1$192$vtk_disk_source_get_inner_radius(::vtkDiskSource const &disk) noexcept {
  double (*vtk_disk_source_get_inner_radius$)(::vtkDiskSource const &) = ::vtk_disk_source_get_inner_radius;
  return vtk_disk_source_get_inner_radius$(disk);
}

void cxxbridge1$192$vtk_disk_source_set_outer_radius(::vtkDiskSource &disk, double radius) noexcept {
  void (*vtk_disk_source_set_outer_radius$)(::vtkDiskSource &, double) = ::vtk_disk_source_set_outer_radius;
  vtk_disk_source_set_outer_radius$(disk, radius);
}

double cxxbridge1$192$vtk_disk_source_get_outer_radius(::vtkDiskSource const &disk) noexcept {
  double (*vtk_disk_source_get_outer_radius$)(::vtkDiskSource const &) = ::vtk_disk_source_get_outer_radius;
  return vtk_disk_source_get_outer_radius$(disk);
}

void cxxbridge1$192$vtk_disk_source_set_radial_resolution(::vtkDiskSource &disk, ::std::int32_t r) noexcept {
  void (*vtk_disk_source_set_radial_resolution$)(::vtkDiskSource &, ::std::int32_t) = ::vtk_disk_source_set_radial_resolution;
  vtk_disk_source_set_radial_resolution$(disk, r);
}

::std::int32_t cxxbridge1$192$vtk_disk_source_get_radial_resolution(::vtkDiskSource const &disk) noexcept {
  ::std::int32_t (*vtk_disk_source_get_radial_resolution$)(::vtkDiskSource const &) = ::vtk_disk_source_get_radial_resolution;
  return vtk_disk_source_get_radial_resolution$(disk);
}

void cxxbridge1$192$vtk_disk_source_set_circumferential_resolution(::vtkDiskSource &disk, ::std::int32_t r) noexcept {
  void (*vtk_disk_source_set_circumferential_resolution$)(::vtkDiskSource &, ::std::int32_t) = ::vtk_disk_source_set_circumferential_resolution;
  vtk_disk_source_set_circumferential_resolution$(disk, r);
}

::std::int32_t cxxbridge1$192$vtk_disk_source_get_circumferential_resolution(::vtkDiskSource const &disk) noexcept {
  ::std::int32_t (*vtk_disk_source_get_circumferential_resolution$)(::vtkDiskSource const &) = ::vtk_disk_source_get_circumferential_resolution;
  return vtk_disk_source_get_circumferential_resolution$(disk);
}

void cxxbridge1$192$vtk_disk_source_set_center(::vtkDiskSource &disk, double x, double y, double z) noexcept {
  void (*vtk_disk_source_set_center$)(::vtkDiskSource &, double, double, double) = ::vtk_disk_source_set_center;
  vtk_disk_source_set_center$(disk, x, y, z);
}

void cxxbridge1$192$vtk_disk_source_get_center(::vtkDiskSource const &disk, double &x, double &y, double &z) noexcept {
  void (*vtk_disk_source_get_center$)(::vtkDiskSource const &, double &, double &, double &) = ::vtk_disk_source_get_center;
  vtk_disk_source_get_center$(disk, x, y, z);
}

void cxxbridge1$192$vtk_disk_source_set_normal(::vtkDiskSource &disk, double x, double y, double z) noexcept {
  void (*vtk_disk_source_set_normal$)(::vtkDiskSource &, double, double, double) = ::vtk_disk_source_set_normal;
  vtk_disk_source_set_normal$(disk, x, y, z);
}

void cxxbridge1$192$vtk_disk_source_get_normal(::vtkDiskSource const &disk, double &x, double &y, double &z) noexcept {
  void (*vtk_disk_source_get_normal$)(::vtkDiskSource const &, double &, double &, double &) = ::vtk_disk_source_get_normal;
  vtk_disk_source_get_normal$(disk, x, y, z);
}

::vtkAlgorithmOutput *cxxbridge1$192$vtk_disk_source_get_output_port(::vtkDiskSource &disk) noexcept {
  ::vtkAlgorithmOutput *(*vtk_disk_source_get_output_port$)(::vtkDiskSource &) = ::vtk_disk_source_get_output_port;
  return vtk_disk_source_get_output_port$(disk);
}
} // extern "C"