// AUTO-GENERATED BY cxxbridge
#include "vtk_cube_source.h"
#include "vtk_algorithm_output.h"

#ifdef __GNUC__
#pragma GCC diagnostic ignored "-Wmissing-declarations"
#ifdef __clang__
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"
#endif // __clang__
#endif // __GNUC__

using vtkCubeSource = ::vtkCubeSource;
using vtkAlgorithmOutput = ::vtkAlgorithmOutput;

extern "C" {
::vtkCubeSource *cxxbridge1$192$vtk_cube_source_new() noexcept {
  ::vtkCubeSource *(*vtk_cube_source_new$)() = ::vtk_cube_source_new;
  return vtk_cube_source_new$();
}

void cxxbridge1$192$vtk_cube_source_delete(::vtkCubeSource &cube) noexcept {
  void (*vtk_cube_source_delete$)(::vtkCubeSource &) = ::vtk_cube_source_delete;
  vtk_cube_source_delete$(cube);
}

void cxxbridge1$192$vtk_cube_source_set_x_length(::vtkCubeSource &cube, double length) noexcept {
  void (*vtk_cube_source_set_x_length$)(::vtkCubeSource &, double) = ::vtk_cube_source_set_x_length;
  vtk_cube_source_set_x_length$(cube, length);
}

double cxxbridge1$192$vtk_cube_source_get_x_length(::vtkCubeSource const &cube) noexcept {
  double (*vtk_cube_source_get_x_length$)(::vtkCubeSource const &) = ::vtk_cube_source_get_x_length;
  return vtk_cube_source_get_x_length$(cube);
}

void cxxbridge1$192$vtk_cube_source_set_y_length(::vtkCubeSource &cube, double length) noexcept {
  void (*vtk_cube_source_set_y_length$)(::vtkCubeSource &, double) = ::vtk_cube_source_set_y_length;
  vtk_cube_source_set_y_length$(cube, length);
}

double cxxbridge1$192$vtk_cube_source_get_y_length(::vtkCubeSource const &cube) noexcept {
  double (*vtk_cube_source_get_y_length$)(::vtkCubeSource const &) = ::vtk_cube_source_get_y_length;
  return vtk_cube_source_get_y_length$(cube);
}

void cxxbridge1$192$vtk_cube_source_set_z_length(::vtkCubeSource &cube, double length) noexcept {
  void (*vtk_cube_source_set_z_length$)(::vtkCubeSource &, double) = ::vtk_cube_source_set_z_length;
  vtk_cube_source_set_z_length$(cube, length);
}

double cxxbridge1$192$vtk_cube_source_get_z_length(::vtkCubeSource const &cube) noexcept {
  double (*vtk_cube_source_get_z_length$)(::vtkCubeSource const &) = ::vtk_cube_source_get_z_length;
  return vtk_cube_source_get_z_length$(cube);
}

void cxxbridge1$192$vtk_cube_source_set_center(::vtkCubeSource &cube, double x, double y, double z) noexcept {
  void (*vtk_cube_source_set_center$)(::vtkCubeSource &, double, double, double) = ::vtk_cube_source_set_center;
  vtk_cube_source_set_center$(cube, x, y, z);
}

void cxxbridge1$192$vtk_cube_source_get_center(::vtkCubeSource const &cube, double &x, double &y, double &z) noexcept {
  void (*vtk_cube_source_get_center$)(::vtkCubeSource const &, double &, double &, double &) = ::vtk_cube_source_get_center;
  vtk_cube_source_get_center$(cube, x, y, z);
}

void cxxbridge1$192$vtk_cube_source_set_bounds(::vtkCubeSource &cube, double xmin, double xmax, double ymin, double ymax, double zmin, double zmax) noexcept {
  void (*vtk_cube_source_set_bounds$)(::vtkCubeSource &, double, double, double, double, double, double) = ::vtk_cube_source_set_bounds;
  vtk_cube_source_set_bounds$(cube, xmin, xmax, ymin, ymax, zmin, zmax);
}

void cxxbridge1$192$vtk_cube_source_get_bounds(::vtkCubeSource const &cube, double &xmin, double &xmax, double &ymin, double &ymax, double &zmin, double &zmax) noexcept {
  void (*vtk_cube_source_get_bounds$)(::vtkCubeSource const &, double &, double &, double &, double &, double &, double &) = ::vtk_cube_source_get_bounds;
  vtk_cube_source_get_bounds$(cube, xmin, xmax, ymin, ymax, zmin, zmax);
}

::vtkAlgorithmOutput *cxxbridge1$192$vtk_cube_source_get_output_port(::vtkCubeSource &cube) noexcept {
  ::vtkAlgorithmOutput *(*vtk_cube_source_get_output_port$)(::vtkCubeSource &) = ::vtk_cube_source_get_output_port;
  return vtk_cube_source_get_output_port$(cube);
}
} // extern "C"