// AUTO-GENERATED BY cxxbridge
#include "vtk_camera.h"

#ifdef __GNUC__
#pragma GCC diagnostic ignored "-Wmissing-declarations"
#ifdef __clang__
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"
#endif // __clang__
#endif // __GNUC__

using vtkCamera = ::vtkCamera;

extern "C" {
::vtkCamera *cxxbridge1$192$camera_new() noexcept {
  ::vtkCamera *(*camera_new$)() = ::camera_new;
  return camera_new$();
}

void cxxbridge1$192$camera_delete(::vtkCamera &camera) noexcept {
  void (*camera_delete$)(::vtkCamera &) = ::camera_delete;
  camera_delete$(camera);
}

void cxxbridge1$192$camera_set_position(::vtkCamera &camera, double x, double y, double z) noexcept {
  void (*camera_set_position$)(::vtkCamera &, double, double, double) = ::camera_set_position;
  camera_set_position$(camera, x, y, z);
}

void cxxbridge1$192$camera_get_position(::vtkCamera &camera, double &x, double &y, double &z) noexcept {
  void (*camera_get_position$)(::vtkCamera &, double &, double &, double &) = ::camera_get_position;
  camera_get_position$(camera, x, y, z);
}

void cxxbridge1$192$camera_set_focal_point(::vtkCamera &camera, double x, double y, double z) noexcept {
  void (*camera_set_focal_point$)(::vtkCamera &, double, double, double) = ::camera_set_focal_point;
  camera_set_focal_point$(camera, x, y, z);
}

void cxxbridge1$192$camera_get_focal_point(::vtkCamera &camera, double &x, double &y, double &z) noexcept {
  void (*camera_get_focal_point$)(::vtkCamera &, double &, double &, double &) = ::camera_get_focal_point;
  camera_get_focal_point$(camera, x, y, z);
}

void cxxbridge1$192$camera_set_view_up(::vtkCamera &camera, double x, double y, double z) noexcept {
  void (*camera_set_view_up$)(::vtkCamera &, double, double, double) = ::camera_set_view_up;
  camera_set_view_up$(camera, x, y, z);
}

void cxxbridge1$192$camera_get_view_up(::vtkCamera &camera, double &x, double &y, double &z) noexcept {
  void (*camera_get_view_up$)(::vtkCamera &, double &, double &, double &) = ::camera_get_view_up;
  camera_get_view_up$(camera, x, y, z);
}

void cxxbridge1$192$camera_azimuth(::vtkCamera &camera, double angle) noexcept {
  void (*camera_azimuth$)(::vtkCamera &, double) = ::camera_azimuth;
  camera_azimuth$(camera, angle);
}

void cxxbridge1$192$camera_elevation(::vtkCamera &camera, double angle) noexcept {
  void (*camera_elevation$)(::vtkCamera &, double) = ::camera_elevation;
  camera_elevation$(camera, angle);
}

void cxxbridge1$192$camera_roll(::vtkCamera &camera, double angle) noexcept {
  void (*camera_roll$)(::vtkCamera &, double) = ::camera_roll;
  camera_roll$(camera, angle);
}

void cxxbridge1$192$camera_zoom(::vtkCamera &camera, double factor) noexcept {
  void (*camera_zoom$)(::vtkCamera &, double) = ::camera_zoom;
  camera_zoom$(camera, factor);
}

void cxxbridge1$192$camera_dolly(::vtkCamera &camera, double factor) noexcept {
  void (*camera_dolly$)(::vtkCamera &, double) = ::camera_dolly;
  camera_dolly$(camera, factor);
}

void cxxbridge1$192$camera_set_clipping_range(::vtkCamera &camera, double near, double far) noexcept {
  void (*camera_set_clipping_range$)(::vtkCamera &, double, double) = ::camera_set_clipping_range;
  camera_set_clipping_range$(camera, near, far);
}

void cxxbridge1$192$camera_get_clipping_range(::vtkCamera &camera, double &near, double &far) noexcept {
  void (*camera_get_clipping_range$)(::vtkCamera &, double &, double &) = ::camera_get_clipping_range;
  camera_get_clipping_range$(camera, near, far);
}
} // extern "C"