// AUTO-GENERATED BY cxxbridge
#include "vtk_axes_actor.h"

#ifdef __GNUC__
#pragma GCC diagnostic ignored "-Wmissing-declarations"
#ifdef __clang__
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"
#endif // __clang__
#endif // __GNUC__

using vtkAxesActor = ::vtkAxesActor;

extern "C" {
::vtkAxesActor *cxxbridge1$192$axes_actor_new() noexcept {
  ::vtkAxesActor *(*axes_actor_new$)() = ::axes_actor_new;
  return axes_actor_new$();
}

void cxxbridge1$192$axes_actor_delete(::vtkAxesActor &actor) noexcept {
  void (*axes_actor_delete$)(::vtkAxesActor &) = ::axes_actor_delete;
  axes_actor_delete$(actor);
}
} // extern "C"